### ISSUE TITLE
latte-dock latest git freeze on Arch after gcc update

### ISSUE THREAD

**Issue by omni6** [psifidotos/Latte-Dock#1022]
Hello,

since the last git update my latte-dock freezes after seconds, sometimes open applications also freeze till latte is killed. Cpu load for latte is constantly at 13% .
Removed all config files and tried with clean profile, same result.
Moving to the release version fixed it, i think this can be same issue as #1021. 

Maybe this helps

```
(gdb) start
Temporary breakpoint 4 at 0x5555555a27f0: file /tmp/makepkg/latte-dock-git/src/latte-dock/app/main.cpp, line 59.
Starting program: /usr/bin/latte-dock 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
qt.core.logging: Ignoring malformed logging rule: '’*=false’'
QML debugging is enabled. Only use this in a safe environment.

Temporary breakpoint 4, main () at /tmp/makepkg/latte-dock-git/src/latte-dock/app/main.cpp:59
59      in /tmp/makepkg/latte-dock-git/src/latte-dock/app/main.cpp
(gdb) continue
Continuing.
[New Thread 0x7fffe1a4c700 (LWP 9649)]
[New Thread 0x7fffda86c700 (LWP 9668)]
Icon theme "ubuntu-mono-dark" not found.
Icon theme "gnome" not found.
[New Thread 0x7fffd8be4700 (LWP 9695)]
[New Thread 0x7fffc80b9700 (LWP 9696)]
[New Thread 0x7fffc78b8700 (LWP 9697)]
[New Thread 0x7fffc70b7700 (LWP 9698)]
[New Thread 0x7fffc68b6700 (LWP 9699)]
[New Thread 0x7fffc60b5700 (LWP 9700)]
[New Thread 0x7fffc58b4700 (LWP 9701)]
[New Thread 0x7fffc50b3700 (LWP 9702)]
[New Thread 0x7fffc48b2700 (LWP 9703)]
[Thread 0x7fffc48b2700 (LWP 9703) exited]
[New Thread 0x7fffc48b2700 (LWP 9773)]
[New Thread 0x7fff9c7b1700 (LWP 9774)]
[New Thread 0x7fff8f842700 (LWP 9818)]
[New Thread 0x7fff8d4c7700 (LWP 9822)]
[Thread 0x7fff8d4c7700 (LWP 9822) exited]
[New Thread 0x7fff8d4c7700 (LWP 9841)]
[New Thread 0x7fff7a103700 (LWP 9865)]
[New Thread 0x7fff67fff700 (LWP 9950)]
^C
Thread 1 "latte-dock" received signal SIGINT, Interrupt.
0x00007ffff267eec6 in QObjectPrivate::isSignalConnected (checkDeclarative=false, signal_index=36, this=0x55555a608ef0) at kernel/qobject_p.h:260
260     kernel/qobject_p.h: Datei oder Verzeichnis nicht gefunden.
(gdb) backtrace
#0  0x00007ffff267eec6 in QObjectPrivate::isSignalConnected(unsigned int, bool) const (checkDeclarative=false, signal_index=36, this=0x55555a608ef0) at kernel/qobject_p.h:260
#1  0x00007ffff267eec6 in QMetaObject::activate(QObject*, int, int, void**) (sender=sender@entry=0x7fffdc007880, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0)
    at kernel/qobject.cpp:3648
#2  0x00007ffff267fd89 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) (sender=sender@entry=0x7fffdc007880, m=m@entry=0x5555558684c0 <Latte::ScreenEdgeGhostWindow::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0) at kernel/qobject.cpp:3629
#3  0x000055555562c309 in Latte::ScreenEdgeGhostWindow::edgeTriggered() (this=this@entry=0x7fffdc007880)
    at /tmp/makepkg/latte-dock-git/src/latte-dock/build/app/latte-dock_autogen/647R6NJRF7/moc_screenedgeghostwindow.cpp:139
#4  0x00005555556292b1 in Latte::ScreenEdgeGhostWindow::event(QEvent*) (this=0x7fffdc007880, e=0x7fffffffce00) at /tmp/makepkg/latte-dock-git/src/latte-dock/app/dock/screenedgeghostwindow.cpp:206
#5  0x00007ffff33d407c in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x555555891050, receiver=receiver@entry=0x7fffdc007880, e=e@entry=0x7fffffffce00) at kernel/qapplication.cpp:3732
#6  0x00007ffff33dba56 in QApplication::notify(QObject*, QEvent*) (this=0x7fffffffdc90, receiver=0x7fffdc007880, e=0x7fffffffce00) at kernel/qapplication.cpp:3491
#7  0x00007ffff264ed60 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=receiver@entry=0x7fffdc007880, event=event@entry=0x7fffffffce00) at kernel/qcoreapplication.cpp:1050
#8  0x00007ffff2bcedcd in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x7fffffffce00, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:234
#9  0x00007ffff2bcedcd in QWindowPrivate::create(bool, unsigned long long) (this=<optimized out>, recursive=recursive@entry=false, nativeHandle=nativeHandle@entry=0) at kernel/qwindow.cpp:541
#10 0x00007ffff2bcef1e in QWindow::create() (this=<optimized out>) at kernel/qwindow.cpp:629
#11 0x00007ffff2bcef46 in QWindow::winId() const (this=<optimized out>) at kernel/qwindow.cpp:645
#12 0x0000555555628766 in Latte::ScreenEdgeGhostWindow::<lambda()>::operator() (__closure=0x55555a74ab90) at /tmp/makepkg/latte-dock-git/src/latte-dock/app/dock/screenedgeghostwindow.cpp:82
#13 0x0000555555628766 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, Latte::ScreenEdgeGhostWindow::ScreenEdgeGhostWindow(Latte::DockView*)::<lambda()> >::call (arg=<optimized out>, f=...) at /usr/include/qt/QtCore/qobjectdefs_impl.h:130
#14 0x0000555555628766 in QtPrivate::Functor<Latte::ScreenEdgeGhostWindow::ScreenEdgeGhostWindow(Latte::DockView*)::<lambda()>, 0>::call<QtPrivate::List<>, void> (arg=<optimized out>, f=...)
    at /usr/include/qt/QtCore/qobjectdefs_impl.h:240
#15 0x0000555555628766 in QtPrivate::QFunctorSlotObject<Latte::ScreenEdgeGhostWindow::ScreenEdgeGhostWindow(Latte::DockView*)::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=<optimized out>, this_=0x55555a74ab80, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/qt/QtCore/qobjectdefs_impl.h:423
#16 0x00007ffff267f7af in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffcfb0, r=0x7fffdc007880, this=0x55555a74ab80) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:378
#17 0x00007ffff267f7af in QMetaObject::activate(QObject*, int, int, void**) (sender=sender@entry=0x7fffdc007880, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=12, argv=argv@entry=0x7fffffffcfb0) at kernel/qobject.cpp:3750
#18 0x00007ffff267fd89 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) (sender=sender@entry=0x7fffdc007880, m=m@entry=0x7ffff32681c0 <QWindow::staticMetaObject>, local_signal_index=local_signal_---Type <return> to continue, or q <return> to quit---
index@entry=12, argv=argv@entry=0x7fffffffcfb0) at kernel/qobject.cpp:3629
#19 0x00007ffff2bc8563 in QWindow::visibleChanged(bool) (this=this@entry=0x7fffdc007880, _t1=<optimized out>) at .moc/moc_qwindow.cpp:755
#20 0x00007ffff2bd0354 in QWindowPrivate::setVisible(bool) (this=0x55555a608ef0, visible=<optimized out>) at kernel/qwindow.cpp:334
#21 0x0000555555629149 in Latte::ScreenEdgeGhostWindow::ScreenEdgeGhostWindow(Latte::DockView*) (this=0x7fffdc007880, view=<optimized out>)
    at /tmp/makepkg/latte-dock-git/src/latte-dock/app/dock/screenedgeghostwindow.cpp:94
#22 0x000055555561f861 in Latte::VisibilityManagerPrivate::createEdgeGhostWindow() (this=0x555556cd5e10) at /tmp/makepkg/latte-dock-git/src/latte-dock/app/dock/visibilitymanager.cpp:936
#23 0x00005555556276aa in Latte::VisibilityManagerPrivate::setMode(Latte::Dock::Visibility) (this=0x555556cd5e10, mode=Latte::Dock::DodgeMaximized)
    at /tmp/makepkg/latte-dock-git/src/latte-dock/app/dock/visibilitymanager.cpp:240
#24 0x00005555556282ec in Latte::VisibilityManagerPrivate::restoreConfig()::{lambda()#2}::operator()() const (__closure=<optimized out>)
    at /tmp/makepkg/latte-dock-git/src/latte-dock/app/dock/visibilitymanager.cpp:596
#25 0x00005555556282ec in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, Latte::VisibilityManagerPrivate::restoreConfig()::{lambda()#2}>::call({lambda()#2}&, void**) (arg=<optimized out>, f=...) at /usr/include/qt/QtCore/qobjectdefs_impl.h:130
#26 0x00005555556282ec in QtPrivate::Functor<Latte::VisibilityManagerPrivate::restoreConfig()::{lambda()#2}, 0>::call<QtPrivate::List<>, void>({lambda()#2}&, void*, {lambda()#2}&*) (arg=<optimized out>, f=...)
    at /usr/include/qt/QtCore/qobjectdefs_impl.h:240
#27 0x00005555556282ec in QtPrivate::QFunctorSlotObject<Latte::VisibilityManagerPrivate::restoreConfig()::{lambda()#2}, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/qt/QtCore/qobjectdefs_impl.h:423
#28 0x00007ffff267f7af in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffd460, r=0x555556cd5e10, this=0x555556cd0180) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:378
#29 0x00007ffff267f7af in QMetaObject::activate(QObject*, int, int, void**) (sender=sender@entry=0x555556cd5ed0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffd460) at kernel/qobject.cpp:3750
#30 0x00007ffff267fd89 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) (sender=sender@entry=0x555556cd5ed0, m=m@entry=0x7ffff2ab25a0 <QTimer::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffd460) at kernel/qobject.cpp:3629
#31 0x00007ffff268c578 in QTimer::timeout(QTimer::QPrivateSignal) (this=this@entry=0x555556cd5ed0, _t1=...) at .moc/moc_qtimer.cpp:200
#32 0x00007ffff268c8e9 in QTimer::timerEvent(QTimerEvent*) (this=0x555556cd5ed0, e=<optimized out>) at kernel/qtimer.cpp:255
#33 0x00007ffff268008b in QObject::event(QEvent*) (this=0x555556cd5ed0, e=<optimized out>) at kernel/qobject.cpp:1269
#34 0x00007ffff33d407c in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x555555891050, receiver=receiver@entry=0x555556cd5ed0, e=e@entry=0x7fffffffd760) at kernel/qapplication.cpp:3732
#35 0x00007ffff33dba56 in QApplication::notify(QObject*, QEvent*) (this=0x7fffffffdc90, receiver=0x555556cd5ed0, e=0x7fffffffd760) at kernel/qapplication.cpp:3491
---Type <return> to continue, or q <return> to quit---
#36 0x00007ffff264ed60 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x555556cd5ed0, event=event@entry=0x7fffffffd760) at kernel/qcoreapplication.cpp:1050
#37 0x00007ffff26aa6f8 in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x7fffffffd760, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:234
#38 0x00007ffff26aa6f8 in QTimerInfoList::activateTimers() (this=0x555555900660) at kernel/qtimerinfo_unix.cpp:643
#39 0x00007ffff26aaef2 in timerSourceDispatch(GSource*, GSourceFunc, gpointer) (source=<optimized out>) at kernel/qeventdispatcher_glib.cpp:182
#40 0x00007fffe8d4d368 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#41 0x00007fffe8d4d5b1 in  () at /usr/lib/libglib-2.0.so.0
#42 0x00007fffe8d4d63e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#43 0x00007ffff26ab2b1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x5555559057d0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#44 0x00007fffe4259c62 in QPAEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x5555559057d0, flags=...) at qeventdispatcher_glib.cpp:69
#45 0x00007ffff264d39b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffd9d0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#46 0x00007ffff2656798 in QCoreApplication::exec() () at kernel/qcoreapplication.cpp:1338
#47 0x00005555555a3cab in main (argc=<optimized out>, argv=<optimized out>) at /tmp/makepkg/latte-dock-git/src/latte-dock/app/main.cpp:255
#48 0x00007ffff16e106b in __libc_start_main () at /usr/lib/libc.so.6
#49 0x00005555555a465a in _start () at /tmp/makepkg/latte-dock-git/src/latte-dock/app/dock/visibilitymanager.cpp:1130

```

**Comment by psifidotos** [comment]
Hm.... Disable at Tweaks-> Use kwin screen edges

does that help?

**Comment by omni6** [comment]
I don't come to the config window... freeze.
After start 2-3 seconds no matter if i hover or not.

**Comment by psifidotos** [comment]
What is the qt version?

**Comment by psifidotos** [comment]
I mean the Latte screen edges option in Tweaks, idont have any other ideas

**Comment by omni6** [comment]
Qt 5.10.1

**Comment by omni6** [comment]
@ArchangeGabriel 
any ideas?

**Comment by ArchangeGabriel** [comment]
Hum? I don’t get why you pinged me here… I don’t use this software, and neither am I packaging it.

**Comment by omni6** [comment]
i realized too late, sorry

**Comment by iicurtis** [comment]
Any clue what might be going on here? I tried rebuilding the latest git version after the GCC upgrade, but I still get the freeze. I rebuilt the Apr 13th version as well. They all freeze in seconds. This is not likely to be a Latte issue, but I would like to get this up and running if you have any hints.

**Comment by psifidotos** [comment]
If this occurs because of a gcc update in Arch, I have no idea except if qt or kde frameworks have been built with different version

**Comment by omni6** [comment]
First thing to do: wait a couple of days. Possible this issue terminates itself (hopefully).

**Comment by omni6** [comment]
Ok (bad) news, it is definitively gcc that cause this issue. I have downgraded gcc from  to 7.3.1 and recompiled latest git, all is fine again.

**Comment by psifidotos** [comment]
> Ok (bad) news, it is definitively gcc that cause this issue. 

for me that is good news... :) how about clang ? if you compile with clang?

**Comment by omni6** [comment]
with clang it doesn't freeze it crashes.
Lets wait until everything is sure compiled with new gcc version...

**Comment by omni6** [comment]
T have to re-recompile everything with debug flags, tomorrow...

**Comment by omni6** [comment]
backtrace from crash with clang:

```
(gdb) start
Temporary breakpoint 1 at 0xe124e: file /tmp/makepkg/latte-dock-git/src/latte-dock/app/main.cpp, line 68.
Starting program: /usr/bin/latte-dock 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
qt.core.logging: Ignoring malformed logging rule: '’*=false’'
QML debugging is enabled. Only use this in a safe environment.

Temporary breakpoint 1, main (argc=1, argv=0x7fffffffdee8) at /tmp/makepkg/latte-dock-git/src/latte-dock/app/main.cpp:68
68      /tmp/makepkg/latte-dock-git/src/latte-dock/app/main.cpp: Datei oder Verzeichnis nicht gefunden.
(gdb) continue
Continuing.
[New Thread 0x7fffe1a4f700 (LWP 18021)]
[New Thread 0x7fffda86c700 (LWP 18058)]
Icon theme "ubuntu-mono-dark" not found.
Icon theme "gnome" not found.
[New Thread 0x7fffd8be4700 (LWP 18060)]
[New Thread 0x7fffc80b9700 (LWP 18079)]
[New Thread 0x7fffc78b8700 (LWP 18080)]
[New Thread 0x7fffc70b7700 (LWP 18081)]
[New Thread 0x7fffc68b6700 (LWP 18082)]
[New Thread 0x7fffc60b5700 (LWP 18083)]
[New Thread 0x7fffc58b4700 (LWP 18084)]
[New Thread 0x7fffc50b3700 (LWP 18085)]
[New Thread 0x7fffc48b2700 (LWP 18086)]
[Thread 0x7fffc48b2700 (LWP 18086) exited]
[New Thread 0x7fffc48b2700 (LWP 18148)]
[New Thread 0x7fff9c7b1700 (LWP 18149)]
[New Thread 0x7fff8f816700 (LWP 18209)]
[New Thread 0x7fff8d499700 (LWP 18225)]
[Thread 0x7fff8d499700 (LWP 18225) exited]
[New Thread 0x7fff8d499700 (LWP 18257)]
[New Thread 0x7fff7a104700 (LWP 18263)]
[New Thread 0x7fff67fff700 (LWP 18318)]

Thread 1 "latte-dock" received signal SIGSEGV, Segmentation fault.
0x0000555555634f40 in QRect::QRect (this=<optimized out>) at /usr/include/qt/QtCore/qrect.h:60
60          Q_DECL_CONSTEXPR QRect() Q_DECL_NOTHROW : x1(0), y1(0), x2(-1), y2(-1) {}
(gdb) backtrace
#0  0x0000555555634f40 in QRect::QRect() (this=<optimized out>) at /usr/include/qt/QtCore/qrect.h:60
#1  0x0000555555634f40 in Latte::ScreenEdgeGhostWindow::showWithMask() (this=0x55555a73f7c0) at /tmp/makepkg/latte-dock-git/src/latte-dock/app/dock/screenedgeghostwindow.cpp:221
#2  0x0000555555885a78 in vtable for Latte::ScreenEdgeGhostWindow ()
#3  0x000055555a73f7c0 in  ()
#4  0x000055555a73f7c0 in  ()
#5  0x00007ffff33d407c in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x5555558b0050, receiver=0x7fffffffcfc0, receiver@entry=0x55555a73f7c0, e=e@entry=0x7fffffffcfc0)
    at kernel/qapplication.cpp:3732
#6  0x00007ffff33dba56 in QApplication::notify(QObject*, QEvent*) (this=0x7fffffffdce8, receiver=0x55555a73f7c0, e=0x7fffffffcfc0) at kernel/qapplication.cpp:3491
#7  0x00007ffff264ed60 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=receiver@entry=0x55555a73f7c0, event=event@entry=0x7fffffffcfc0) at kernel/qcoreapplication.cpp:1050
#8  0x00007ffff2bcedcd in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x7fffffffcfc0, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:234
#9  0x00007ffff2bcedcd in QWindowPrivate::create(bool, unsigned long long) (this=<optimized out>, recursive=recursive@entry=false, nativeHandle=nativeHandle@entry=0) at kernel/qwindow.cpp:541
#10 0x00007ffff2bcef1e in QWindow::create() (this=<optimized out>) at kernel/qwindow.cpp:629
#11 0x00007ffff2bcef46 in QWindow::winId() const (this=<optimized out>) at kernel/qwindow.cpp:645
#12 0x00005555556350bc in Latte::ScreenEdgeGhostWindow::ScreenEdgeGhostWindow(Latte::DockView*)::$_1::operator()() const (this=<optimized out>)
    at /tmp/makepkg/latte-dock-git/src/latte-dock/app/dock/screenedgeghostwindow.cpp:82
#13 0x00005555556350bc in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, Latte::ScreenEdgeGhostWindow::ScreenEdgeGhostWindow(Latte::DockView*)::$_1>::call(Latte::ScreenEdgeGhostWindow::ScreenEdgeGhostWindow(Latte::DockView*)::$_1&, void**) (f=..., arg=<optimized out>) at /usr/include/qt/QtCore/qobjectdefs_impl.h:130
#14 0x00005555556350bc in _ZN9QtPrivate7FunctorIZN5Latte21ScreenEdgeGhostWindowC1EPNS1_8DockViewEE3$_1Li0EE4callINS_4ListIJEEEvEEvRS5_PvPSB_ (f=..., arg=<optimized out>)
    at /usr/include/qt/QtCore/qobjectdefs_impl.h:240
#15 0x00005555556350bc in _ZN9QtPrivate18QFunctorSlotObjectIZN5Latte21ScreenEdgeGhostWindowC1EPNS1_8DockViewEE3$_1Li0ENS_4ListIJEEEvE4implEiPNS_15QSlotObjectBaseEP7QObjectPPvPb (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/qt/QtCore/qobjectdefs_impl.h:423
#16 0x00007ffff267f7af in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffd170, r=0x55555a73f7c0, this=0x55555a792940) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:378
#17 0x00007ffff267f7af in QMetaObject::activate(QObject*, int, int, void**) (sender=sender@entry=0x55555a73f7c0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=12, argv=argv@entry=0x7fffffffd170) at kernel/qobject.cpp:3750
#18 0x00007ffff267fd89 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) (sender=sender@entry=0x55555a73f7c0, m=m@entry=0x7ffff32681c0 <QWindow::staticMetaObject>, local_signal_index=local_signal_index@entry=12, argv=argv@entry=0x7fffffffd170) at kernel/qobject.cpp:3629
---Type <return> to continue, or q <return> to quit---
#19 0x00007ffff2bc8563 in QWindow::visibleChanged(bool) (this=this@entry=0x55555a73f7c0, _t1=<optimized out>) at .moc/moc_qwindow.cpp:755
#20 0x00007ffff2bd0354 in QWindowPrivate::setVisible(bool) (this=0x55555a67edc0, visible=<optimized out>) at kernel/qwindow.cpp:334
#21 0x00005555556347f3 in Latte::ScreenEdgeGhostWindow::ScreenEdgeGhostWindow(Latte::DockView*) (this=0x55555a73f7c0, view=<optimized out>)
    at /tmp/makepkg/latte-dock-git/src/latte-dock/app/dock/screenedgeghostwindow.cpp:94
#22 0x000055555563022b in Latte::VisibilityManagerPrivate::createEdgeGhostWindow() (this=0x555556dec0f0) at /tmp/makepkg/latte-dock-git/src/latte-dock/app/dock/visibilitymanager.cpp:936
#23 0x0000555555632cac in Latte::VisibilityManagerPrivate::setMode(Latte::Dock::Visibility) (this=0x555556dec0f0, mode=<optimized out>)
    at /tmp/makepkg/latte-dock-git/src/latte-dock/app/dock/visibilitymanager.cpp:240
#24 0x00005555556330d9 in Latte::VisibilityManagerPrivate::restoreConfig()::{lambda()#2}::operator()() const (this=<optimized out>) at /tmp/makepkg/latte-dock-git/src/latte-dock/app/dock/visibilitymanager.cpp:604
#25 0x00005555556330d9 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, Latte::VisibilityManagerPrivate::restoreConfig()::{lambda()#2}>::call({lambda()#2}&, void**) (f=..., arg=<optimized out>) at /usr/include/qt/QtCore/qobjectdefs_impl.h:130
#26 0x00007ffff267f7af in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffd550, r=0x555556dec0f0, this=0x555556de63b0) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:378
#27 0x00007ffff267f7af in QMetaObject::activate(QObject*, int, int, void**) (sender=sender@entry=0x555556dec1b0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffd550) at kernel/qobject.cpp:3750
#28 0x00007ffff267fd89 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) (sender=sender@entry=0x555556dec1b0, m=m@entry=0x7ffff2ab25a0 <QTimer::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffd550) at kernel/qobject.cpp:3629
#29 0x00007ffff268c578 in QTimer::timeout(QTimer::QPrivateSignal) (this=this@entry=0x555556dec1b0, _t1=...) at .moc/moc_qtimer.cpp:200
#30 0x00007ffff268c8e9 in QTimer::timerEvent(QTimerEvent*) (this=0x555556dec1b0, e=<optimized out>) at kernel/qtimer.cpp:255
#31 0x00007ffff268008b in QObject::event(QEvent*) (this=0x555556dec1b0, e=<optimized out>) at kernel/qobject.cpp:1269
#32 0x00007ffff33d407c in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x5555558b0050, receiver=receiver@entry=0x555556dec1b0, e=e@entry=0x7fffffffd850) at kernel/qapplication.cpp:3732
#33 0x00007ffff33dba56 in QApplication::notify(QObject*, QEvent*) (this=0x7fffffffdce8, receiver=0x555556dec1b0, e=0x7fffffffd850) at kernel/qapplication.cpp:3491
#34 0x00007ffff264ed60 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x555556dec1b0, event=event@entry=0x7fffffffd850) at kernel/qcoreapplication.cpp:1050
#35 0x00007ffff26aa6f8 in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x7fffffffd850, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:234
#36 0x00007ffff26aa6f8 in QTimerInfoList::activateTimers() (this=0x5555558fe9f0) at kernel/qtimerinfo_unix.cpp:643
#37 0x00007ffff26aaef2 in timerSourceDispatch(GSource*, GSourceFunc, gpointer) (source=<optimized out>) at kernel/qeventdispatcher_glib.cpp:182
#38 0x00007fffe8d50368 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#39 0x00007fffe8d505b1 in  () at /usr/lib/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#40 0x00007fffe8d5063e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#41 0x00007ffff26ab2b1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x5555559247e0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#42 0x00007fffe425cc62 in QPAEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x5555559247e0, flags=...) at qeventdispatcher_glib.cpp:69
#43 0x00007ffff264d39b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffdac0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#44 0x00007ffff2656798 in QCoreApplication::exec() () at kernel/qcoreapplication.cpp:1338
#45 0x0000555555637de8 in main(int, char**) (argc=1, argv=<optimized out>) at /tmp/makepkg/latte-dock-git/src/latte-dock/app/main.cpp:255
(gdb) 

```

**Comment by omni6** [comment]
lol, works like a charm. will try gcc soon...

**Comment by omni6** [comment]
solved, thank you!
