### ISSUE TITLE
Adding the network monitor applet to latte makes it crash (not happening in plasma panel)

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#143]
This is the source code of network monitor:

[https://github.com/kotelnik/plasma-applet-network-monitor](https://github.com/kotelnik/plasma-applet-network-monitor
)

Could you please see if it crashes the latte dock in your system as well?

**Comment by psifidotos** [comment]
I cant confirm it ... The plasmoid works ok in adding it and in restart it latte...

![image](https://cloud.githubusercontent.com/assets/2216474/22626803/8fd3ea2e-ebbe-11e6-8134-ee9f2470af5c.png)

**Comment by kupiqu** [comment]
mmm, that's weird, I wonder why it is crashing my latte :/

do you think it could be related to the icon size?  (mine is set to 32px)

**Comment by psifidotos** [comment]
is it working for 64px. in your system?

**Comment by kupiqu** [comment]
is there a way to get some info about the underlying reason that makes latte crash?

**Comment by kupiqu** [comment]
going to try increasing size

**Comment by kupiqu** [comment]
it also crashes for 64 px :(

**Comment by psifidotos** [comment]
Crashing Debuging steps:

- Install ddd
- ddd latte-dock
- in ddd window write and execute, run
- when it crashes, click status from the menu, backtrace
- This will show you a window with numbered lines, this could be helpful for us...

**Comment by kupiqu** [comment]
do I need to install plasma dbg packages?

**Comment by psifidotos** [comment]
no, you dont need to install any...

90% if it is in our side of code it will appear in the backtrace

**Comment by kupiqu** [comment]
Actually, I find trouble in linking the debugger with the source code of latte. Do I need to specify it somehow? I guess I have to install it with Debug as an argument. I am doing it now but it is Running qmllint forever :/

The issue so far seems to be related to qmlincubator.h, which is not found (I have it installed in my computer but it is searched wherever I start latte from, my home directory being default when I execute latte from krunner).

**Comment by kupiqu** [comment]
I solved my issue with qmllint, I was missing qtdeclarative5-dev-tools. However, the debugger is still failing to link latte's source code.

**Comment by kupiqu** [comment]
I think the issue is that 'somebody' is calling qqmlincubator.cpp and the most I have is qqmlincubator.h in my system

**Comment by psifidotos** [comment]
Is it crashing when you add it or when latte starts in the beginning?

**Comment by psifidotos** [comment]
did you use ddd as mentioned previously? Can you upload a screenshot of the backtrace?

**Comment by kupiqu** [comment]
it crashes both

![image](https://cloud.githubusercontent.com/assets/3875196/22646400/3ae7597a-ec3a-11e6-9003-9f10dc14dd8b.png)

ddd also opens a popup window saying qqmlincubator.cpp file or directory does not exist (or alike, translating)

**Comment by kupiqu** [comment]
That file indeed does not exist, only the qqmlincubator.h file does in my system

**Comment by kupiqu** [comment]
This is what I get from the kde bug report system, for the case it is useful:

```
Application: Latte Dock (latte-dock), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7ff3825fa8c0 (LWP 15027))]

Thread 11 (Thread 0x7ff2f0f42700 (LWP 15048)):
#0  0x00007ff38ff73b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ff38b18038c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ff38b18049c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ff390aa975b in QEventDispatcherGlib::processEvents (this=0x7ff2e40008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:425
#4  0x00007ff390a540ba in QEventLoop::exec (this=this@entry=0x7ff2f0f41ce0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#5  0x00007ff390883f64 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:507
#6  0x00007ff30c01d975 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/XmlListModel/libqmlxmllistmodelplugin.so
#7  0x00007ff390888b48 in QThreadPrivate::start (arg=0x3fb1d70) at thread/qthread_unix.cpp:368
#8  0x00007ff38c9cc6ba in start_thread (arg=0x7ff2f0f42700) at pthread_create.c:333
#9  0x00007ff38ff7f82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 10 (Thread 0x7ff2f27e4700 (LWP 15043)):
#0  QEventDispatcherGlib::processEvents (this=0x7ff2ec0008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:424
#1  0x00007ff390a540ba in QEventLoop::exec (this=this@entry=0x7ff2f27e3d00, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#2  0x00007ff390883f64 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:507
#3  0x00007ff390888b48 in QThreadPrivate::start (arg=0x3cca090) at thread/qthread_unix.cpp:368
#4  0x00007ff38c9cc6ba in start_thread (arg=0x7ff2f27e4700) at pthread_create.c:333
#5  0x00007ff38ff7f82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 9 (Thread 0x7ff30ffff700 (LWP 15042)):
#0  0x00007ff38ff73b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ff38b18038c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ff38b18049c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ff390aa975b in QEventDispatcherGlib::processEvents (this=0x7ff3080008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:425
#4  0x00007ff390a540ba in QEventLoop::exec (this=this@entry=0x7ff30fffed00, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#5  0x00007ff390883f64 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:507
#6  0x00007ff390888b48 in QThreadPrivate::start (arg=0x3023eb0) at thread/qthread_unix.cpp:368
#7  0x00007ff38c9cc6ba in start_thread (arg=0x7ff30ffff700) at pthread_create.c:333
#8  0x00007ff38ff7f82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 8 (Thread 0x7ff31db62700 (LWP 15034)):
#0  0x00007ff38ff73b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ff38b18038c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ff38b18049c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ff390aa975b in QEventDispatcherGlib::processEvents (this=0x7ff3140008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:425
#4  0x00007ff390a540ba in QEventLoop::exec (this=this@entry=0x7ff31db61d00, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#5  0x00007ff390883f64 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:507
#6  0x00007ff390888b48 in QThreadPrivate::start (arg=0x2fbff60) at thread/qthread_unix.cpp:368
#7  0x00007ff38c9cc6ba in start_thread (arg=0x7ff31db62700) at pthread_create.c:333
#8  0x00007ff38ff7f82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 7 (Thread 0x7ff31e363700 (LWP 15033)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ff3619b89a4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#2  0x00007ff3619b8bfa in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#3  0x00007ff362ac11d1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#4  0x00007ff38c9cc6ba in start_thread (arg=0x7ff31e363700) at pthread_create.c:333
#5  0x00007ff38ff7f82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 6 (Thread 0x7ff31eb64700 (LWP 15032)):
#0  0x00007ff38ff6f69d in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ff38b1c36f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ff38b17fe74 in g_main_context_check () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ff38b180330 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ff38b18049c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ff390aa975b in QEventDispatcherGlib::processEvents (this=0x7ff3180008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:425
#6  0x00007ff390a540ba in QEventLoop::exec (this=this@entry=0x7ff31eb63d00, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#7  0x00007ff390883f64 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:507
#8  0x00007ff390888b48 in QThreadPrivate::start (arg=0x2fbc590) at thread/qthread_unix.cpp:368
#9  0x00007ff38c9cc6ba in start_thread (arg=0x7ff31eb64700) at pthread_create.c:333
#10 0x00007ff38ff7f82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7ff35f47d700 (LWP 15031)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ff362a915ab in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#2  0x00007ff362a915e9 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#3  0x00007ff38c9cc6ba in start_thread (arg=0x7ff35f47d700) at pthread_create.c:333
#4  0x00007ff38ff7f82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7ff377fff700 (LWP 15030)):
#0  0x00007ff38b1c4a94 in g_mutex_unlock () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ff38b1804a6 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ff390aa975b in QEventDispatcherGlib::processEvents (this=0x7ff36c0008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:425
#3  0x00007ff390a540ba in QEventLoop::exec (this=this@entry=0x7ff377ffece0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#4  0x00007ff390883f64 in QThread::exec (this=this@entry=0x2316f50) at thread/qthread.cpp:507
#5  0x00007ff3926b7bf5 in QQmlThreadPrivate::run (this=0x2316f50) at qml/ftw/qqmlthread.cpp:147
#6  0x00007ff390888b48 in QThreadPrivate::start (arg=0x2316f50) at thread/qthread_unix.cpp:368
#7  0x00007ff38c9cc6ba in start_thread (arg=0x7ff377fff700) at pthread_create.c:333
#8  0x00007ff38ff7f82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7ff37df52700 (LWP 15029)):
#0  0x00007ff38ff73b61 in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ff38b18038c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ff38b18049c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ff390aa975b in QEventDispatcherGlib::processEvents (this=0x7ff3700008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:425
#4  0x00007ff390a540ba in QEventLoop::exec (this=this@entry=0x7ff37df51cd0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#5  0x00007ff390883f64 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:507
#6  0x00007ff3943b1735 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#7  0x00007ff390888b48 in QThreadPrivate::start (arg=0x7ff394425d60) at thread/qthread_unix.cpp:368
#8  0x00007ff38c9cc6ba in start_thread (arg=0x7ff37df52700) at pthread_create.c:333
#9  0x00007ff38ff7f82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7ff37fade700 (LWP 15028)):
#0  0x00007ff38ff73b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ff3933adc62 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007ff3933af8d7 in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007ff381e32d79 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007ff390888b48 in QThreadPrivate::start (arg=0x2250270) at thread/qthread_unix.cpp:368
#5  0x00007ff38c9cc6ba in start_thread (arg=0x7ff37fade700) at pthread_create.c:333
#6  0x00007ff38ff7f82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7ff3825fa8c0 (LWP 15027)):
[KCrash Handler]
#6  QScopedPointer<QObjectData, QScopedPointerDeleter<QObjectData> >::data (this=<error reading variable: Cannot access memory at address 0x30>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qscopedpointer.h:141
#7  qGetPtrHelper<QScopedPointer<QObjectData> > (p=<error reading variable: Cannot access memory at address 0x30>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:980
#8  QQmlEngine::d_func (this=<error reading variable: Cannot access memory at address 0x30>) at ../../include/QtQml/5.7.1/QtQml/private/../../../../../src/qml/qml/qqmlengine.h:158
#9  QQmlEnginePrivate::get (e=<error reading variable: Cannot access memory at address 0x30>) at ../../include/QtQml/5.7.1/QtQml/private/../../../../../src/qml/qml/qqmlengine_p.h:403
#10 QQmlIncubator::clear (this=this@entry=0x41d9480) at qml/qqmlincubator.cpp:569
#11 0x00007ff3926da2e8 in QQmlDelegateModelPrivate::releaseIncubator (this=this@entry=0x41c2aa0, incubationTask=0x41d9480) at types/qqmldelegatemodel.cpp:846
#12 0x00007ff3926dcafa in QQmlDelegateModelPrivate::itemsRemoved (this=this@entry=0x41c2aa0, removes=..., translatedRemoves=translatedRemoves@entry=0x7ffddc567810, movedItems=movedItems@entry=0x0) at types/qqmldelegatemodel.cpp:1320
#13 0x00007ff3926dcf12 in QQmlDelegateModelPrivate::itemsRemoved (this=this@entry=0x41c2aa0, removes=...) at types/qqmldelegatemodel.cpp:1357
#14 0x00007ff3926de638 in QQmlDelegateModel::_q_itemsRemoved (this=<optimized out>, index=0, count=1) at types/qqmldelegatemodel.cpp:1389
#15 0x00007ff3926decc8 in QQmlDelegateModel::_q_rowsRemoved (this=<optimized out>, parent=..., begin=<optimized out>, end=<optimized out>) at types/qqmldelegatemodel.cpp:1539
#16 0x00007ff392702155 in QQmlDelegateModel::qt_static_metacall (_o=_o@entry=0x41e4350, _c=_c@entry=QMetaObject::InvokeMetaMethod, _id=_id@entry=10, _a=_a@entry=0x7ffddc567b20) at .moc/moc_qqmldelegatemodel_p.cpp:196
#17 0x00007ff3927028e8 in QQmlDelegateModel::qt_metacall (this=0x41e4350, _c=QMetaObject::InvokeMetaMethod, _id=10, _a=0x7ffddc567b20) at .moc/moc_qqmldelegatemodel_p.cpp:334
#18 0x00007ff390a81014 in QMetaObject::activate (sender=sender@entry=0x41e3200, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=12, argv=argv@entry=0x7ffddc567b20) at kernel/qobject.cpp:3755
#19 0x00007ff390a81837 in QMetaObject::activate (sender=sender@entry=0x41e3200, m=m@entry=0x7ff390c9ad80 <QAbstractItemModel::staticMetaObject>, local_signal_index=local_signal_index@entry=12, argv=argv@entry=0x7ffddc567b20) at kernel/qobject.cpp:3602
#20 0x00007ff390af6d84 in QAbstractItemModel::rowsRemoved (this=this@entry=0x41e3200, _t1=..., _t2=0, _t3=0) at .moc/moc_qabstractitemmodel.cpp:615
#21 0x00007ff3909fddbb in QAbstractItemModel::endRemoveRows (this=this@entry=0x41e3200) at itemmodels/qabstractitemmodel.cpp:2715
#22 0x00007ff3926e6bad in QQmlListModel::emitItemsRemoved (this=0x41e3200, index=0, count=1) at types/qqmllistmodel.cpp:1797
#23 0x00007ff392703afd in QQmlListModel::qt_static_metacall (_o=_o@entry=0x41e3200, _c=_c@entry=QMetaObject::InvokeMetaMethod, _id=_id@entry=1, _a=_a@entry=0x7ffddc567da0) at .moc/moc_qqmllistmodel_p.cpp:123
#24 0x00007ff392703d68 in QQmlListModel::qt_metacall (this=0x41e3200, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x7ffddc567da0) at .moc/moc_qqmllistmodel_p.cpp:206
#25 0x00007ff392672d29 in QQmlObjectOrGadget::metacall (this=this@entry=0x7ffddc568100, type=type@entry=QMetaObject::InvokeMetaMethod, index=index@entry=56, argv=argv@entry=0x7ffddc567da0) at qml/qqmlpropertycache.cpp:1547
#26 0x00007ff39260252b in CallMethod (object=..., index=56, returnType=returnType@entry=43, argCount=argCount@entry=0, argTypes=argTypes@entry=0x0, engine=engine@entry=0x230ba10, callArgs=0x7ff3770004c0) at jsruntime/qv4qobjectwrapper.cpp:1155
#27 0x00007ff3926029e7 in CallPrecise (object=..., data=..., engine=engine@entry=0x230ba10, callArgs=callArgs@entry=0x7ff3770004c0) at jsruntime/qv4qobjectwrapper.cpp:1392
#28 0x00007ff392603365 in QV4::QObjectMethod::callInternal (this=<optimized out>, callData=<optimized out>) at jsruntime/qv4qobjectwrapper.cpp:1871
#29 0x00007ff392619b31 in QV4::Object::call (d=0x7ff3770004c0, this=<optimized out>) at jsruntime/qv4object_p.h:332
#30 QV4::Runtime::callProperty (engine=0x230ba10, nameIndex=<optimized out>, callData=0x7ff3770004c0) at jsruntime/qv4runtime.cpp:1030
#31 0x00007ff2f02e7119 in ?? ()
#32 0x00007ff377000478 in ?? ()
#33 0x00007ff377000420 in ?? ()
#34 0x00007ff3770003f0 in ?? ()
#35 0x00007ff377000470 in ?? ()
#36 0x00007ff377000358 in ?? ()
#37 0x00007ff39258f1bd in memcpy (__len=<optimized out>, __src=0x7ff377000508, __dest=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/string3.h:53
#38 QV4::ExecutionContext::newCallContext (this=0x7ff377000420, function=<optimized out>, callData=0x7ff377000508) at jsruntime/qv4context.cpp:84
#39 0x00007ff3925b4e8f in QV4::ScriptFunction::call (that=<optimized out>, callData=<optimized out>) at jsruntime/qv4functionobject.cpp:472
#40 0x00007ff392619702 in QV4::Object::call (d=0x7ff377000420, this=0x7ff377000470) at jsruntime/qv4object_p.h:332
#41 QV4::Runtime::callActivationProperty (engine=0x230ba10, nameIndex=<optimized out>, callData=0x7ff377000420) at jsruntime/qv4runtime.cpp:980
#42 0x00007ff2f02ea0b3 in ?? ()
#43 0x00007ff377000370 in ?? ()
#44 0x00007ff3770003d8 in ?? ()
#45 0x00007ff377000358 in ?? ()
#46 0x00007ff39258f1bd in memcpy (__len=<optimized out>, __src=0x7ff377000460, __dest=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/string3.h:53
#47 QV4::ExecutionContext::newCallContext (this=0x7ff377000388, function=<optimized out>, callData=0x7ff377000460) at jsruntime/qv4context.cpp:84
#48 0x00007ff3925b4e8f in QV4::ScriptFunction::call (that=<optimized out>, callData=<optimized out>) at jsruntime/qv4functionobject.cpp:472
#49 0x00007ff392619702 in QV4::Object::call (d=0x7ff377000388, this=0x7ff3770003d8) at jsruntime/qv4object_p.h:332
#50 QV4::Runtime::callActivationProperty (engine=0x230ba10, nameIndex=<optimized out>, callData=0x7ff377000388) at jsruntime/qv4runtime.cpp:980
#51 0x00007ff2f02ed7d3 in ?? ()
#52 0x00007ff3770003f8 in ?? ()
#53 0x00007ff30e9ffe30 in ?? ()
#54 0x000000000230ba10 in ?? ()
#55 0x00007ff3925911c7 in QV4::Object::get (hasProperty=0x7ff377000388, name=0x7ffddc568610, this=<optimized out>) at ../../include/QtQml/5.7.1/QtQml/private/../../../../../src/qml/jsruntime/qv4object_p.h:306
#56 QV4::ExecutionContext::getPropertyAndBase (this=0x0, name=0x7ffddc568610, base=0x7ff377000010) at jsruntime/qv4context.cpp:548
#57 0x00007ff30eb43810 in ?? ()
#58 0x00007ff377000370 in ?? ()
#59 0x0000000000000000 in ?? ()
```

**Comment by psifidotos** [comment]
If i would guess this is inside the qml plasmoid and it is an early removal or activation from a delegatemodel or xmllistmodel...

I would propose to forward all this to the official developer... if he finds out that this is in our side, we will definitely fix it!!!

**Comment by kupiqu** [comment]
ok, i'll do... what seems a bit weird though is that it fails in latte but not in plasma

**Comment by kupiqu** [comment]
Suprisingly, I did add the applet again to latte, but this time to the side panel instead of top panel, and it worked!

So, it's very weird, the applet does not like the top panel in latte, it works in plasma, and it is not due to the icon size, both side and top panel tested with the same size in latte, one works and the other fails.

Hope this helps to figure out what is going wrong here, whether in latte or in the applet...

**Comment by psifidotos** [comment]
in my system, it is ok...

![image](https://cloud.githubusercontent.com/assets/2216474/22706686/d7a70ba4-ed78-11e6-94c6-c872a243e466.png)

**Comment by kupiqu** [comment]
yeah, it is very weird

**Comment by psifidotos** [comment]
are you using closed source or open source graphics driver?

**Comment by kupiqu** [comment]
it's intel

**Comment by psifidotos** [comment]
I looked in the applets main.qml code... i think i know what is happening, the applet in the begin tries to create the model of the available devices but during that time the visual creation of that model is happening... it could be solved by safe guarding the startup... either with some flags or even by adding a timer...

**Comment by psifidotos** [comment]
you could try:

[main.qml.txt](https://github.com/psifidotos/Latte-Dock/files/758826/main.qml.txt)

uninstall previous plasmoid...
substitute file **package/contents/ui/main.qml** with the version I sent you, dont forget to remove the **_.txt_** extension from my file
and after that reinstall the plasmoid

**Comment by psifidotos** [comment]
in my system because of this patch it even loads much much faster!

**Comment by kupiqu** [comment]
It works!!

Thanks a lot

**Comment by psifidotos** [comment]
;)

**Comment by kupiqu** [comment]
ufff, finally...!

you are a master :)

**Comment by psifidotos** [comment]
;)

I will send a pull request also to the main developer I hope it accepts it...

**Comment by kupiqu** [comment]
That's very nice, in the issue I opened there, I indicated that you have a fix for the issue here, but much better a pull request there.

I also hope it gets accepted :)

**Comment by psifidotos** [comment]
I can just uploaded the Pull request you can comment the issue you mentioned in the comments of the pull request

**Comment by kupiqu** [comment]
Sure, thanks
