### ISSUE TITLE
[Crash] - Occasionally segmentation fault when playing with visibility modes

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#548]
![screenshot_20170617_105456](https://user-images.githubusercontent.com/24593950/27252274-8315632c-535a-11e7-93c1-f493e4bc9705.png)
file:///home/Ivan/Immagini/Screenshot_20170617_105456.png.T16115

```
Application: Latte Dock (latte-dock), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f0b63476940 (LWP 10138))]

Thread 8 (Thread 0x7f0b21a18700 (LWP 15489)):
#0  0x00007f0b5b68551d in read () at /lib64/libc.so.6
#1  0x00007f0b52901931 in pa_read () at /usr/lib64/pulseaudio/libpulsecommon-9.0.so
#2  0x00007f0b553633be in pa_mainloop_prepare () at /usr/lib64/libpulse.so.0
#3  0x00007f0b55363dd2 in pa_mainloop_iterate () at /usr/lib64/libpulse.so.0
#4  0x00007f0b55363e90 in pa_mainloop_run () at /usr/lib64/libpulse.so.0
#5  0x00007f0b55372006 in  () at /usr/lib64/libpulse.so.0
#6  0x00007f0b52930408 in  () at /usr/lib64/pulseaudio/libpulsecommon-9.0.so
#7  0x00007f0b58d0b744 in start_thread () at /lib64/libpthread.so.0
#8  0x00007f0b5b691d3d in clone () at /lib64/libc.so.6

Thread 7 (Thread 0x7f0b2d159700 (LWP 10185)):
#0  0x00007f0b5b68949d in poll () at /lib64/libc.so.6
#1  0x00007f0b565fd314 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f0b565fd42c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f0b5c49e4db in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#4  0x00007f0b5c44d03b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f0b5c293d1a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007f0b2e582887 in KCupsConnection::run() () at /usr/lib64/libkcupslib.so
#7  0x00007f0b5c29819d in  () at /usr/lib64/libQt5Core.so.5
#8  0x00007f0b58d0b744 in start_thread () at /lib64/libpthread.so.0
#9  0x00007f0b5b691d3d in clone () at /lib64/libc.so.6

Thread 6 (Thread 0x7f0b33a4f700 (LWP 10166)):
#0  0x00007f0b5b68949d in poll () at /lib64/libc.so.6
#1  0x00007f0b565fd314 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f0b565fd42c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f0b5c49e4db in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#4  0x00007f0b5c44d03b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f0b5c293d1a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007f0b5c29819d in  () at /usr/lib64/libQt5Core.so.5
#7  0x00007f0b58d0b744 in start_thread () at /lib64/libpthread.so.0
#8  0x00007f0b5b691d3d in clone () at /lib64/libc.so.6

Thread 5 (Thread 0x7f0b34250700 (LWP 10165)):
#0  0x00007f0b5b68551d in read () at /lib64/libc.so.6
#1  0x00007f0b5663d750 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f0b565fce49 in g_main_context_check () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f0b565fd2a8 in  () at /usr/lib64/libglib-2.0.so.0
#4  0x00007f0b565fd42c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#5  0x00007f0b5c49e4db in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#6  0x00007f0b5c44d03b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#7  0x00007f0b5c293d1a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#8  0x00007f0b3488f4e5 in  () at /usr/lib64/qt5/qml/QtQuick/XmlListModel/libqmlxmllistmodelplugin.so
#9  0x00007f0b5c29819d in  () at /usr/lib64/libQt5Core.so.5
#10 0x00007f0b58d0b744 in start_thread () at /lib64/libpthread.so.0
#11 0x00007f0b5b691d3d in clone () at /lib64/libc.so.6

Thread 4 (Thread 0x7f0b4ade5700 (LWP 10149)):
#0  0x00007f0b5663e8b4 in g_mutex_unlock () at /usr/lib64/libglib-2.0.so.0
#1  0x00007f0b565fcd4b in g_main_context_check () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f0b565fd2a8 in  () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f0b565fd42c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#4  0x00007f0b5c49e4db in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f0b5c44d03b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#6  0x00007f0b5c293d1a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#7  0x00007f0b604397b8 in  () at /usr/lib64/libQt5Qml.so.5
#8  0x00007f0b5c29819d in  () at /usr/lib64/libQt5Core.so.5
#9  0x00007f0b58d0b744 in start_thread () at /lib64/libpthread.so.0
#10 0x00007f0b5b691d3d in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7f0b4c469700 (LWP 10141)):
#0  0x00007f0b565fa672 in  () at /usr/lib64/libglib-2.0.so.0
#1  0x00007f0b565fc8fb in g_main_context_prepare () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f0b565fd230 in  () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f0b565fd42c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#4  0x00007f0b5c49e4db in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f0b5c44d03b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#6  0x00007f0b5c293d1a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#7  0x00007f0b5c9277e5 in  () at /usr/lib64/libQt5DBus.so.5
#8  0x00007f0b5c29819d in  () at /usr/lib64/libQt5Core.so.5
#9  0x00007f0b58d0b744 in start_thread () at /lib64/libpthread.so.0
#10 0x00007f0b5b691d3d in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7f0b4d4ad700 (LWP 10140)):
#0  0x00007f0b5b68949d in poll () at /lib64/libc.so.6
#1  0x00007f0b61e0c3e2 in  () at /usr/lib64/libxcb.so.1
#2  0x00007f0b61e0dfcf in xcb_wait_for_event () at /usr/lib64/libxcb.so.1
#3  0x00007f0b4edc5639 in  () at /usr/lib64/libQt5XcbQpa.so.5
#4  0x00007f0b5c29819d in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007f0b58d0b744 in start_thread () at /lib64/libpthread.so.0
#6  0x00007f0b5b691d3d in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7f0b63476940 (LWP 10138)):
[KCrash Handler]
#6  0x00007f0b6094808e in QQuickItemPrivate::addToDirtyList() () at /usr/lib64/libQt5Quick.so.5
#7  0x00007f0b60948138 in QQuickItemPrivate::dirty(QQuickItemPrivate::DirtyType) () at /usr/lib64/libQt5Quick.so.5
#8  0x00007f0b6095eec8 in  () at /usr/lib64/libQt5Quick.so.5
#9  0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#10 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#11 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#12 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#13 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#14 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#15 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#16 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#17 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#18 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#19 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#20 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#21 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#22 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#23 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#24 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#25 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#26 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#27 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#28 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#29 0x00007f0b6095ee96 in  () at /usr/lib64/libQt5Quick.so.5
#30 0x00007f0b6096189c in QQuickWindowPrivate::syncSceneGraph() () at /usr/lib64/libQt5Quick.so.5
#31 0x00007f0b608f81f5 in  () at /usr/lib64/libQt5Quick.so.5
#32 0x00007f0b608f8e4d in  () at /usr/lib64/libQt5Quick.so.5
#33 0x00007f0b5cca69de in QWindow::event(QEvent*) () at /usr/lib64/libQt5Gui.so.5
#34 0x00007f0b6096ae95 in QQuickWindow::event(QEvent*) () at /usr/lib64/libQt5Quick.so.5
#35 0x0000000000444355 in Latte::DockView::event(QEvent*) ()
#36 0x00007f0b5d40dafc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#37 0x00007f0b5d414840 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#38 0x00007f0b5c44ebc5 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#39 0x00007f0b5cc9c1f1 in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) () at /usr/lib64/libQt5Gui.so.5
#40 0x00007f0b5cc9cd1d in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib64/libQt5Gui.so.5
#41 0x00007f0b5cc7b83b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Gui.so.5
#42 0x00007f0b4ee16960 in  () at /usr/lib64/libQt5XcbQpa.so.5
#43 0x00007f0b565fd134 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#44 0x00007f0b565fd388 in  () at /usr/lib64/libglib-2.0.so.0
#45 0x00007f0b565fd42c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#46 0x00007f0b5c49e4bc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#47 0x00007f0b5c44d03b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#48 0x00007f0b5c4551f4 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#49 0x000000000042909e in main ()

```

**Comment by psifidotos** [comment]
how? just clicking on different modes or setting them?

@audoban any ideas?

**Comment by psifidotos** [comment]
personally this backtrace is totally useless for me... I dont know if ddd can return better results...

what qt version are you using?

**Comment by JenaPlinsky** [comment]
![spectacle q20530](https://user-images.githubusercontent.com/24593950/27253012-8001888a-536b-11e7-9355-89d7d9ea072e.png)

**Comment by JenaPlinsky** [comment]
> how? just clicking on different modes or setting them?

If I remember well ... settling them

**Comment by audoban** [comment]
@psifidotos confirmed, but i need more debugging for find the bug.

**Comment by psifidotos** [comment]
>  confirmed, but i need more debugging for find the bug.

unfortunately I cant reproduce in my system

**Comment by audoban** [comment]
Hard to reproduce.

**Comment by psifidotos** [comment]
can you please try to reproduce this... I have uploaded 2-3 different crash fixes that could influence this...

I will open this again of course if we didnt catch it yet
