### ISSUE TITLE
[Feature Request] - runtime loading of the layouts instead of closing/starting Latte

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#565]

**Comment by audoban** [comment]
@psifidotos How do you suggest achieving this?

**Comment by psifidotos** [comment]
for copy function I used importLayout of corona, plasmashell is using loadLayout from corona to achieve this...

importLayout adds containments in the current corona state
loadLayout replaces all containments with those imported, we can watch plasmashell how exactly deletes the old containments and adds the new ones

my proposal is that this should triggered only from the config window... it is nice to keep the current
--import  functionality for external loading layouts

**Comment by psifidotos** [comment]
https://github.com/KDE/plasma-framework/blob/master/src/plasma/corona.cpp

loadLayout function

**Comment by audoban** [comment]
Sounds good, ok I'm agree.

**Comment by psifidotos** [comment]
@audoban it is ready... you can test it at **_dynamicLayouts_** branch

please take some precusions before testing the branch, I accidentaly deleted all my /home/<user> directory when I was trying to remove the temp directories.... :( I am lucky that the most important files etc are in an external disk but all my user configuration and some partially works here and there are lost... :( 

expect that now everything works ok in my system and I dont have any crashes... the loading is also very fast now...

**Comment by audoban** [comment]
> @psifidotos please take some precusions before testing the branch, I accidentaly deleted all my /home/ directory when I was trying to remove the temp directories.... :( I am lucky that the most important files etc are in an external disk but all my user configuration and some partially works here and there are lost... :(

How dangerous to be careful!!!

**Comment by audoban** [comment]
works fine.

**Comment by audoban** [comment]
I was found a crash when I want to load Unity layout:

```
Application: Latte Dock (latte-dock), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f9d8cd78900 (LWP 29347))]

Thread 5 (Thread 0x7f9d6fbbe700 (LWP 4425)):
#0  0x00007f9d7fefcbb6 in ?? () from /usr/lib64/libglib-2.0.so.0
#1  0x00007f9d7feff15b in g_main_context_prepare () from /usr/lib64/libglib-2.0.so.0
#2  0x00007f9d7feffc1b in ?? () from /usr/lib64/libglib-2.0.so.0
#3  0x00007f9d7feffdfc in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#4  0x00007f9d85cfc75b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007f9d85ca5d0a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#6  0x00007f9d85ad805a in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#7  0x00007f9d89cf1d45 in ?? () from /usr/lib64/libQt5Qml.so.5
#8  0x00007f9d85adc73e in ?? () from /usr/lib64/libQt5Core.so.5
#9  0x00007f9d827234e7 in start_thread () from /lib64/libpthread.so.0
#10 0x00007f9d84ec1a2f in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7f9d479da700 (LWP 30419)):
#0  0x00007f9d7ff44b30 in g_mutex_unlock () from /usr/lib64/libglib-2.0.so.0
#1  0x00007f9d7feffc0e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007f9d7feffdfc in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007f9d85cfc75b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007f9d85ca5d0a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007f9d85ad805a in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007f9d555c9f37 in KCupsConnection::run() () from /usr/lib64/libkcupslib.so
#7  0x00007f9d85adc73e in ?? () from /usr/lib64/libQt5Core.so.5
#8  0x00007f9d827234e7 in start_thread () from /lib64/libpthread.so.0
#9  0x00007f9d84ec1a2f in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7f9d75698700 (LWP 29378)):
#0  0x00007f9d84eb3dfd in read () from /lib64/libc.so.6
#1  0x00007f9d7ff437e0 in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007f9d7feff7cb in g_main_context_check () from /usr/lib64/libglib-2.0.so.0
#3  0x00007f9d7feffc90 in ?? () from /usr/lib64/libglib-2.0.so.0
#4  0x00007f9d7feffdfc in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#5  0x00007f9d85cfc75b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#6  0x00007f9d85ca5d0a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#7  0x00007f9d85ad805a in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#8  0x00007f9d86185a45 in ?? () from /usr/lib64/libQt5DBus.so.5
#9  0x00007f9d85adc73e in ?? () from /usr/lib64/libQt5Core.so.5
#10 0x00007f9d827234e7 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f9d84ec1a2f in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f9d77c24700 (LWP 29374)):
#0  0x00007f9d84eb808d in poll () from /lib64/libc.so.6
#1  0x00007f9d8b6ce387 in ?? () from /usr/lib64/libxcb.so.1
#2  0x00007f9d8b6d017a in xcb_wait_for_event () from /usr/lib64/libxcb.so.1
#3  0x00007f9d79b84249 in ?? () from /usr/lib64/libQt5XcbQpa.so.5
#4  0x00007f9d85adc73e in ?? () from /usr/lib64/libQt5Core.so.5
#5  0x00007f9d827234e7 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f9d84ec1a2f in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f9d8cd78900 (LWP 29347)):
[KCrash Handler]
#6  0x00007f9d8a2022d0 in QQuickWindow::maybeUpdate() () from /usr/lib64/libQt5Quick.so.5
#7  0x00007f9d8a1ed39e in QQuickItem::setX(double) () from /usr/lib64/libQt5Quick.so.5
#8  0x00007f9d8a1e3da8 in ?? () from /usr/lib64/libQt5Quick.so.5
#9  0x00007f9d8a1e413a in ?? () from /usr/lib64/libQt5Quick.so.5
#10 0x00007f9d8a1f2d2d in QQuickItem::geometryChanged(QRectF const&, QRectF const&) () from /usr/lib64/libQt5Quick.so.5
#11 0x00007f9d8a1ed6ee in QQuickItem::setWidth(double) () from /usr/lib64/libQt5Quick.so.5
#12 0x00007f9d8a1fbb1a in ?? () from /usr/lib64/libQt5Quick.so.5
#13 0x00007f9d89cdc8e6 in ?? () from /usr/lib64/libQt5Qml.so.5
#14 0x00007f9d89cdce66 in ?? () from /usr/lib64/libQt5Qml.so.5
#15 0x00007f9d89cd9dd3 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () from /usr/lib64/libQt5Qml.so.5
#16 0x00007f9d89cb23e3 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib64/libQt5Qml.so.5
#17 0x00007f9d89c54f45 in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () from /usr/lib64/libQt5Qml.so.5
#18 0x00007f9d85cd3ea0 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#19 0x00007f9d8a1f2daa in QQuickItem::geometryChanged(QRectF const&, QRectF const&) () from /usr/lib64/libQt5Quick.so.5
#20 0x00007f9d8a1ed6ee in QQuickItem::setWidth(double) () from /usr/lib64/libQt5Quick.so.5
#21 0x00007f9d8a1fbb1a in ?? () from /usr/lib64/libQt5Quick.so.5
#22 0x00007f9d89cdc8e6 in ?? () from /usr/lib64/libQt5Qml.so.5
#23 0x00007f9d89cdce66 in ?? () from /usr/lib64/libQt5Qml.so.5
#24 0x00007f9d89cd9dd3 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () from /usr/lib64/libQt5Qml.so.5
#25 0x00007f9d89cb23e3 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib64/libQt5Qml.so.5
#26 0x00007f9d89c54f45 in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () from /usr/lib64/libQt5Qml.so.5
#27 0x00007f9d85cd3ea0 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#28 0x00007f9d89c51010 in QQmlVMEMetaObject::metaCall(QObject*, QMetaObject::Call, int, void**) () from /usr/lib64/libQt5Qml.so.5
#29 0x00007f9d89cdc898 in ?? () from /usr/lib64/libQt5Qml.so.5
#30 0x00007f9d89cdce66 in ?? () from /usr/lib64/libQt5Qml.so.5
#31 0x00007f9d89cd9dd3 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () from /usr/lib64/libQt5Qml.so.5
#32 0x00007f9d89cb23e3 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib64/libQt5Qml.so.5
#33 0x00007f9d89c54f45 in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () from /usr/lib64/libQt5Qml.so.5
#34 0x00007f9d85cd3ea0 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#35 0x00007f9d89c51010 in QQmlVMEMetaObject::metaCall(QObject*, QMetaObject::Call, int, void**) () from /usr/lib64/libQt5Qml.so.5
#36 0x00007f9d89cdc898 in ?? () from /usr/lib64/libQt5Qml.so.5
#37 0x00007f9d89cdce66 in ?? () from /usr/lib64/libQt5Qml.so.5
#38 0x00007f9d89cd9dd3 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () from /usr/lib64/libQt5Qml.so.5
#39 0x00007f9d89cb23e3 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib64/libQt5Qml.so.5
#40 0x00007f9d89c54f45 in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () from /usr/lib64/libQt5Qml.so.5
#41 0x00007f9d85cd3ea0 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#42 0x00007f9d89c51010 in QQmlVMEMetaObject::metaCall(QObject*, QMetaObject::Call, int, void**) () from /usr/lib64/libQt5Qml.so.5
#43 0x00007f9d89cdc898 in ?? () from /usr/lib64/libQt5Qml.so.5
#44 0x00007f9d89cdce66 in ?? () from /usr/lib64/libQt5Qml.so.5
#45 0x00007f9d89cd9dd3 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () from /usr/lib64/libQt5Qml.so.5
#46 0x00007f9d89cb23e3 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib64/libQt5Qml.so.5
#47 0x00007f9d89c54f45 in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () from /usr/lib64/libQt5Qml.so.5
#48 0x00007f9d85cd3ea0 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#49 0x00007f9d89c51010 in QQmlVMEMetaObject::metaCall(QObject*, QMetaObject::Call, int, void**) () from /usr/lib64/libQt5Qml.so.5
#50 0x00007f9d89cdca2f in ?? () from /usr/lib64/libQt5Qml.so.5
#51 0x00007f9d89cdce66 in ?? () from /usr/lib64/libQt5Qml.so.5
#52 0x00007f9d89cd9dd3 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () from /usr/lib64/libQt5Qml.so.5
#53 0x00007f9d89cb23e3 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib64/libQt5Qml.so.5
#54 0x00007f9d89c54f45 in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () from /usr/lib64/libQt5Qml.so.5
#55 0x00007f9d85cd3ea0 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#56 0x00007f9d89c51010 in QQmlVMEMetaObject::metaCall(QObject*, QMetaObject::Call, int, void**) () from /usr/lib64/libQt5Qml.so.5
#57 0x00007f9d89cdca2f in ?? () from /usr/lib64/libQt5Qml.so.5
#58 0x00007f9d89cdce66 in ?? () from /usr/lib64/libQt5Qml.so.5
#59 0x00007f9d89cd9dd3 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () from /usr/lib64/libQt5Qml.so.5
#60 0x00007f9d89cb23e3 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib64/libQt5Qml.so.5
#61 0x00007f9d89c54f45 in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () from /usr/lib64/libQt5Qml.so.5
#62 0x00007f9d85cd3ea0 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#63 0x00007f9d89c53d08 in QQmlData::destroyed(QObject*) () from /usr/lib64/libQt5Qml.so.5
#64 0x00007f9d85cdb157 in QObject::~QObject() () from /usr/lib64/libQt5Core.so.5
#65 0x00007f9d8a1f9d66 in QQuickItem::~QQuickItem() () from /usr/lib64/libQt5Quick.so.5
#66 0x00007f9d5b68861d in ?? () from /usr/lib64/qt5/qml/org/kde/draganddrop/libdraganddropplugin.so
#67 0x00007f9d8c980e1f in PlasmaQuick::AppletQuickItem::~AppletQuickItem() () from /usr/lib64/libKF5PlasmaQuick.so.5
#68 0x00007f9d6fbe416b in ?? () from /usr/lib64/qt5/plugins/plasma/scriptengines/plasma_appletscript_declarative.so
#69 0x00007f9d85cd234b in QObjectPrivate::deleteChildren() () from /usr/lib64/libQt5Core.so.5
#70 0x00007f9d85cdb6ab in QObject::~QObject() () from /usr/lib64/libQt5Core.so.5
#71 0x00007f9d6fbcea64 in ?? () from /usr/lib64/qt5/plugins/plasma/scriptengines/plasma_appletscript_declarative.so
#72 0x00007f9d8b02d650 in ?? () from /usr/lib64/libKF5Plasma.so.5
#73 0x00007f9d8b02d859 in ?? () from /usr/lib64/libKF5Plasma.so.5
#74 0x00007f9d8b01e619 in Plasma::Applet::~Applet() () from /usr/lib64/libKF5Plasma.so.5
#75 0x00007f9d8b022649 in Plasma::Containment::~Containment() () from /usr/lib64/libKF5Plasma.so.5
#76 0x00000000004376e9 in Latte::DockCorona::unload() ()
#77 0x000000000043d274 in Latte::DockCorona::reloadLayout(QString) ()
#78 0x0000000000467711 in Latte::GlobalSettings::importLayoutInternal(QString const&) ()
#79 0x00007f9d85cd467c in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#80 0x00007f9d86ecedae in QDialog::finished(int) () from /usr/lib64/libQt5Widgets.so.5
#81 0x00007f9d86ecf576 in QDialog::done(int) () from /usr/lib64/libQt5Widgets.so.5
#82 0x00007f9d86eacb2a in ?? () from /usr/lib64/libQt5Widgets.so.5
#83 0x00007f9d86eae2f8 in ?? () from /usr/lib64/libQt5Widgets.so.5
#84 0x00007f9d85cd457a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#85 0x00007f9d86e7743f in QDialogButtonBox::clicked(QAbstractButton*) () from /usr/lib64/libQt5Widgets.so.5
#86 0x00007f9d86e779f6 in ?? () from /usr/lib64/libQt5Widgets.so.5
#87 0x00007f9d85cd457a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#88 0x00007f9d86e6ad12 in QAbstractButton::clicked(bool) () from /usr/lib64/libQt5Widgets.so.5
#89 0x00007f9d86e6aefa in ?? () from /usr/lib64/libQt5Widgets.so.5
#90 0x00007f9d86e6c21a in ?? () from /usr/lib64/libQt5Widgets.so.5
#91 0x00007f9d86e6c3e4 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib64/libQt5Widgets.so.5
#92 0x00007f9d86cf8748 in QWidget::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#93 0x00007f9d86cba93c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#94 0x00007f9d86cc220f in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#95 0x00007f9d85ca7578 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#96 0x00007f9d86cc125f in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib64/libQt5Widgets.so.5
#97 0x00007f9d86d1288b in ?? () from /usr/lib64/libQt5Widgets.so.5
#98 0x00007f9d86d14ce1 in ?? () from /usr/lib64/libQt5Widgets.so.5
#99 0x00007f9d86cba93c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#100 0x00007f9d86cc1cb4 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#101 0x00007f9d85ca7578 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#102 0x00007f9d865016db in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib64/libQt5Gui.so.5
#103 0x00007f9d86503025 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib64/libQt5Gui.so.5
#104 0x00007f9d864dcf1b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Gui.so.5
#105 0x00007f9d79be3750 in ?? () from /usr/lib64/libQt5XcbQpa.so.5
#106 0x00007f9d7feffb37 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#107 0x00007f9d7feffd68 in ?? () from /usr/lib64/libglib-2.0.so.0
#108 0x00007f9d7feffdfc in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#109 0x00007f9d85cfc73f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#110 0x00007f9d85ca5d0a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#111 0x00007f9d85cae164 in QCoreApplication::exec() () from /usr/lib64/libQt5Core.so.5
#112 0x0000000000427db8 in main ()
```

**Comment by audoban** [comment]
This issue can be closed?

**Comment by psifidotos** [comment]
I havent merged it yet becausr we are going to update the entire archtecture... i propose to leave it open until the new architecture provides this

**Comment by psifidotos** [comment]
ok... on the other hand, why not... I merged in order for more users also to test the new fast layout switching...

I will open a new issue for the new architecture...
