### ISSUE TITLE
Occasionally crash

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#591]
Running apps:
- vivaldi (active during the crash)
- telegram
- konsole
- dolphin
```
Application: Latte Dock (latte-dock), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f6267b4c940 (LWP 6127))]

Thread 8 (Thread 0x7f6224796700 (LWP 12492)):
#0  0x00007f625fd5f20d in poll () at /lib64/libc.so.6
#1  0x00007f62598260a1 in  () at /usr/lib64/libpulse.so.0
#2  0x00007f625981776c in pa_mainloop_poll () at /usr/lib64/libpulse.so.0
#3  0x00007f6259817dde in pa_mainloop_iterate () at /usr/lib64/libpulse.so.0
#4  0x00007f6259817e90 in pa_mainloop_run () at /usr/lib64/libpulse.so.0
#5  0x00007f6259826006 in  () at /usr/lib64/libpulse.so.0
#6  0x00007f6256bdc408 in  () at /usr/lib64/pulseaudio/libpulsecommon-9.0.so
#7  0x00007f625d3e1744 in start_thread () at /lib64/libpthread.so.0
#8  0x00007f625fd67aad in clone () at /lib64/libc.so.6

Thread 7 (Thread 0x7f62307a5700 (LWP 6369)):
#0  0x00007f625fd5f20d in poll () at /lib64/libc.so.6
#1  0x00007f625acb9314 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f625acb942c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f6260b7913b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#4  0x00007f6260b26c2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f626096b02a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007f6231bce887 in KCupsConnection::run() () at /usr/lib64/libkcupslib.so
#7  0x00007f626096f74d in  () at /usr/lib64/libQt5Core.so.5
#8  0x00007f625d3e1744 in start_thread () at /lib64/libpthread.so.0
#9  0x00007f625fd67aad in clone () at /lib64/libc.so.6

Thread 6 (Thread 0x7f6237a73700 (LWP 6359)):
#0  0x00007f625fd5f20d in poll () at /lib64/libc.so.6
#1  0x00007f625acb9314 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f625acb942c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f6260b7913b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#4  0x00007f6260b26c2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f626096b02a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007f626096f74d in  () at /usr/lib64/libQt5Core.so.5
#7  0x00007f625d3e1744 in start_thread () at /lib64/libpthread.so.0
#8  0x00007f625fd67aad in clone () at /lib64/libc.so.6

Thread 5 (Thread 0x7f6238274700 (LWP 6358)):
#0  0x00007f625acb6670 in  () at /usr/lib64/libglib-2.0.so.0
#1  0x00007f625acb8cef in g_main_context_check () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f625acb92a8 in  () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f625acb942c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#4  0x00007f6260b7913b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f6260b26c2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#6  0x00007f626096b02a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#7  0x00007f62388b54e5 in  () at /usr/lib64/qt5/qml/QtQuick/XmlListModel/libqmlxmllistmodelplugin.so
#8  0x00007f626096f74d in  () at /usr/lib64/libQt5Core.so.5
#9  0x00007f625d3e1744 in start_thread () at /lib64/libpthread.so.0
#10 0x00007f625fd67aad in clone () at /lib64/libc.so.6

Thread 4 (Thread 0x7f624d7d1700 (LWP 6254)):
#0  0x00007f6260b78f57 in  () at /usr/lib64/libQt5Core.so.5
#1  0x00007f625acb8da1 in g_main_context_check () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f625acb92a8 in  () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f625acb942c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#4  0x00007f6260b7913b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f6260b26c2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#6  0x00007f626096b02a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#7  0x00007f6264b10f48 in  () at /usr/lib64/libQt5Qml.so.5
#8  0x00007f626096f74d in  () at /usr/lib64/libQt5Core.so.5
#9  0x00007f625d3e1744 in start_thread () at /lib64/libpthread.so.0
#10 0x00007f625fd67aad in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7f624faa4700 (LWP 6178)):
#0  0x00007f625acb8913 in g_main_context_prepare () at /usr/lib64/libglib-2.0.so.0
#1  0x00007f625acb9230 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f625acb942c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f6260b7913b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#4  0x00007f6260b26c2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f626096b02a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007f6260ffb7e5 in  () at /usr/lib64/libQt5DBus.so.5
#7  0x00007f626096f74d in  () at /usr/lib64/libQt5Core.so.5
#8  0x00007f625d3e1744 in start_thread () at /lib64/libpthread.so.0
#9  0x00007f625fd67aad in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7f6251757700 (LWP 6145)):
#0  0x00007f625fd5f20d in poll () at /lib64/libc.so.6
#1  0x00007f62664e43e2 in  () at /usr/lib64/libxcb.so.1
#2  0x00007f62664e5fcf in xcb_wait_for_event () at /usr/lib64/libxcb.so.1
#3  0x00007f625306f809 in  () at /usr/lib64/libQt5XcbQpa.so.5
#4  0x00007f626096f74d in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007f625d3e1744 in start_thread () at /lib64/libpthread.so.0
#6  0x00007f625fd67aad in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7f6267b4c940 (LWP 6127)):
[KCrash Handler]
#6  0x00007f62650361a0 in QQuickWindow::maybeUpdate() () at /usr/lib64/libQt5Quick.so.5
#7  0x00007f626512c76d in QQuickShaderEffectSource::~QQuickShaderEffectSource() () at /usr/lib64/libQt5Quick.so.5
#8  0x00007f626504cf21 in  () at /usr/lib64/libQt5Quick.so.5
#9  0x00007f6260b50105 in QObjectPrivate::deleteChildren() () at /usr/lib64/libQt5Core.so.5
#10 0x00007f6260b5a33e in QObject::~QObject() () at /usr/lib64/libQt5Core.so.5
#11 0x00007f626502bfcf in QQuickItem::~QQuickItem() () at /usr/lib64/libQt5Quick.so.5
#12 0x00007f626504ccee in  () at /usr/lib64/libQt5Quick.so.5
#13 0x00007f6260b50105 in QObjectPrivate::deleteChildren() () at /usr/lib64/libQt5Core.so.5
#14 0x00007f6260b5a33e in QObject::~QObject() () at /usr/lib64/libQt5Core.so.5
#15 0x00007f626502bfcf in QQuickItem::~QQuickItem() () at /usr/lib64/libQt5Quick.so.5
#16 0x00007f6265048096 in  () at /usr/lib64/libQt5Quick.so.5
#17 0x00007f6260b53780 in QObject::event(QEvent*) () at /usr/lib64/libQt5Core.so.5
#18 0x00007f6265029d7b in QQuickItem::event(QEvent*) () at /usr/lib64/libQt5Quick.so.5
#19 0x00007f6261ae1afc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#20 0x00007f6261ae8840 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#21 0x00007f6260b28935 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#22 0x00007f6260b2af13 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib64/libQt5Core.so.5
#23 0x00007f6260b798f3 in  () at /usr/lib64/libQt5Core.so.5
#24 0x00007f625acb9134 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#25 0x00007f625acb9388 in  () at /usr/lib64/libglib-2.0.so.0
#26 0x00007f625acb942c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#27 0x00007f6260b7911c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#28 0x00007f6260b26c2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#29 0x00007f6260b2f1f4 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#30 0x000000000042bede in main ()
```

**Comment by psifidotos** [comment]
Since when? we havent updated our master branch for a week..

versions, qt, plasma, latte?

**Comment by JenaPlinsky** [comment]
> Since when? we havent updated our master branch for a week..

Lattte is now very stable and this crash happened to me only 2 times

> versions, qt, plasma, latte?

![screenshot_20170715_133524](https://user-images.githubusercontent.com/24593950/28239063-173f5814-6963-11e7-87dc-f66cd3306a80.png)

> versions, qt, plasma, latte?

Master branch

**Comment by psifidotos** [comment]
this could be because of a copied dock!!!! If there is such dock must be deleted, when removing it there will be a crash but afterwards the configuration will be clean!!! The copy function will have to be updated in order to not create such broken configs!!! #616

**Comment by psifidotos** [comment]
this may have been resolved by the new layouts feature and the fixes for the Copy Dock method that wasnt loading correctly the copied docks in the start...

we can reopen it if it stills occurs
