### ISSUE TITLE
[Crash] when I return from the alternative session to the standard session

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#597]
[Crash] when I return from the alternative session to the standard session

```
Application: Latte Dock (latte-dock), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f72aa122940 (LWP 20395))]

Thread 7 (Thread 0x7f7272979700 (LWP 20639)):
#0  0x00007f72a233520d in poll () at /lib64/libc.so.6
#1  0x00007f729d28f314 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f729d28f42c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f72a314f13b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#4  0x00007f72a30fcc2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f72a2f4102a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007f7273da2887 in KCupsConnection::run() () at /usr/lib64/libkcupslib.so
#7  0x00007f72a2f4574d in  () at /usr/lib64/libQt5Core.so.5
#8  0x00007f729f9b7744 in start_thread () at /lib64/libpthread.so.0
#9  0x00007f72a233daad in clone () at /lib64/libc.so.6

Thread 6 (Thread 0x7f727a037700 (LWP 20601)):
#0  0x00007f72a314dbee in QTimerInfoList::timerWait(timespec&) () at /usr/lib64/libQt5Core.so.5
#1  0x00007f72a314ef0e in  () at /usr/lib64/libQt5Core.so.5
#2  0x00007f729d28e95d in g_main_context_prepare () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f729d28f230 in  () at /usr/lib64/libglib-2.0.so.0
#4  0x00007f729d28f42c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#5  0x00007f72a314f13b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#6  0x00007f72a30fcc2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#7  0x00007f72a2f4102a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#8  0x00007f72a2f4574d in  () at /usr/lib64/libQt5Core.so.5
#9  0x00007f729f9b7744 in start_thread () at /lib64/libpthread.so.0
#10 0x00007f72a233daad in clone () at /lib64/libc.so.6

Thread 5 (Thread 0x7f727a838700 (LWP 20600)):
#0  0x00007f729d2d0899 in g_mutex_lock () at /usr/lib64/libglib-2.0.so.0
#1  0x00007f729d28eb51 in g_main_context_query () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f729d28f27f in  () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f729d28f42c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#4  0x00007f72a314f13b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f72a30fcc2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#6  0x00007f72a2f4102a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#7  0x00007f727ae794e5 in  () at /usr/lib64/qt5/qml/QtQuick/XmlListModel/libqmlxmllistmodelplugin.so
#8  0x00007f72a2f4574d in  () at /usr/lib64/libQt5Core.so.5
#9  0x00007f729f9b7744 in start_thread () at /lib64/libpthread.so.0
#10 0x00007f72a233daad in clone () at /lib64/libc.so.6

Thread 4 (Thread 0x7f728fda7700 (LWP 20539)):
#0  0x00007f729d28c6b3 in  () at /usr/lib64/libglib-2.0.so.0
#1  0x00007f729d28e8fb in g_main_context_prepare () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f729d28f230 in  () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f729d28f42c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#4  0x00007f72a314f13b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f72a30fcc2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#6  0x00007f72a2f4102a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#7  0x00007f72a70e6f48 in  () at /usr/lib64/libQt5Qml.so.5
#8  0x00007f72a2f4574d in  () at /usr/lib64/libQt5Core.so.5
#9  0x00007f729f9b7744 in start_thread () at /lib64/libpthread.so.0
#10 0x00007f72a233daad in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7f729207a700 (LWP 20499)):
#0  0x00007f729f9bced0 in pthread_getspecific () at /lib64/libpthread.so.0
#1  0x00007f729d2b3f20 in g_thread_self () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f729d28f41d in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f72a314f13b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#4  0x00007f72a30fcc2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f72a2f4102a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007f72a35d17e5 in  () at /usr/lib64/libQt5DBus.so.5
#7  0x00007f72a2f4574d in  () at /usr/lib64/libQt5Core.so.5
#8  0x00007f729f9b7744 in start_thread () at /lib64/libpthread.so.0
#9  0x00007f72a233daad in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7f7293d2d700 (LWP 20439)):
#0  0x00007f72a233520d in poll () at /lib64/libc.so.6
#1  0x00007f72a8aba3e2 in  () at /usr/lib64/libxcb.so.1
#2  0x00007f72a8abbfcf in xcb_wait_for_event () at /usr/lib64/libxcb.so.1
#3  0x00007f7295645809 in  () at /usr/lib64/libQt5XcbQpa.so.5
#4  0x00007f72a2f4574d in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007f729f9b7744 in start_thread () at /lib64/libpthread.so.0
#6  0x00007f72a233daad in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7f72aa122940 (LWP 20395)):
[KCrash Handler]
#6  0x00007f72a760c1cc in QQuickWindow::maybeUpdate() () at /usr/lib64/libQt5Quick.so.5
#7  0x00007f72a76005bc in QQuickItem::polish() () at /usr/lib64/libQt5Quick.so.5
#8  0x00007f72a760ce78 in  () at /usr/lib64/libQt5Quick.so.5
#9  0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#10 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#11 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#12 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#13 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#14 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#15 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#16 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#17 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#18 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#19 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#20 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#21 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#22 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#23 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#24 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#25 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#26 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#27 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#28 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#29 0x00007f72a760ce46 in  () at /usr/lib64/libQt5Quick.so.5
#30 0x00007f72a760cf13 in QQuickWindow::handleScreenChanged(QScreen*) () at /usr/lib64/libQt5Quick.so.5
#31 0x00007f72a760f654 in  () at /usr/lib64/libQt5Quick.so.5
#32 0x00007f72a3127def in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib64/libQt5Core.so.5
#33 0x00007f72a39496bf in QWindow::screenChanged(QScreen*) () at /usr/lib64/libQt5Gui.so.5
#34 0x00007f72a3949c63 in QWindowPrivate::emitScreenChangedRecursion(QScreen*) () at /usr/lib64/libQt5Gui.so.5
#35 0x00007f72a394ffd5 in QWindowPrivate::setTopLevelScreen(QScreen*, bool) () at /usr/lib64/libQt5Gui.so.5
#36 0x00007f72a3942d60 in QGuiApplicationPrivate::processWindowScreenChangedEvent(QWindowSystemInterfacePrivate::WindowScreenChangedEvent*) () at /usr/lib64/libQt5Gui.so.5
#37 0x00007f72a39470e5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib64/libQt5Gui.so.5
#38 0x00007f72a39258ab in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Gui.so.5
#39 0x00007f7295696e50 in  () at /usr/lib64/libQt5XcbQpa.so.5
#40 0x00007f729d28f134 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#41 0x00007f729d28f388 in  () at /usr/lib64/libglib-2.0.so.0
#42 0x00007f729d28f42c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#43 0x00007f72a314f11c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#44 0x00007f72a30fcc2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#45 0x00007f72a31051f4 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#46 0x000000000042bede in main ()

```

**Comment by psifidotos** [comment]
this should be tested with the new architecture that handles layouts and dynamic layouts... this hasnt landed yet but we are working on it... there will be announcements... the entire master branch has stopped been developed until the new architecture for layouts merges...

such crashes there is a chance that have been fixed in the new architecture... this crash occurs when changing from Alternative to Default session from the latte plasmoid context menu...

**Comment by JenaPlinsky** [comment]
> such crashes there is a chance that have been fixed in the new architecture... 

Great !!!!

> this crash occurs when changing from Alternative to Default session from the latte plasmoid context menu...

Yep ...but also passing from the standard session to the alerative session ...just that I did not have the opportunity to bring back a trace

For the rest latte is very solid and rccks ;)

**Comment by JenaPlinsky** [comment]
Maybe I've already asked this thing ... I do not remember
but can you support the kcrash restart button to re-run latte ? or its support depends from the plasma team

**Comment by psifidotos** [comment]
@JenaPlinsky  is the new infrastructure fixed this for you ?
