### ISSUE TITLE
[Crash] - hovering on the bottom dock of the secondary monitor

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#612]
```
Application: latte-dock (0.6.87)

Qt Version: 5.9.1
Frameworks Version: 5.37.0
Operating System: Linux 4.4.74-1-vanilla x86_64
Distribution: "openSUSE Leap 42.3"

-- Information about the crash:
<In detail, tell us what you were doing  when the application crashed.>

-- Backtrace:
Application: Latte Dock (latte-dock), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f1b48406940 (LWP 6189))]

Thread 6 (Thread 0x7f1b07cb9700 (LWP 7226)):
#0  0x00007f1b4061720d in poll () at /lib64/libc.so.6
#1  0x00007f1b3b571314 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f1b3b57142c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f1b4143113b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#4  0x00007f1b413dec2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f1b4122302a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007f1b453c9f78 in  () at /usr/lib64/libQt5Qml.so.5
#7  0x00007f1b4122774d in  () at /usr/lib64/libQt5Core.so.5
#8  0x00007f1b3dc99744 in start_thread () at /lib64/libpthread.so.0
#9  0x00007f1b4061faad in clone () at /lib64/libc.so.6

Thread 5 (Thread 0x7f1b0c0ed700 (LWP 6320)):
#0  0x00007f1b3b5b2899 in g_mutex_lock () at /usr/lib64/libglib-2.0.so.0
#1  0x00007f1b3b570969 in g_main_context_prepare () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f1b3b571230 in  () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f1b3b57142c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#4  0x00007f1b4143113b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f1b413dec2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#6  0x00007f1b4122302a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#7  0x00007f1b4122774d in  () at /usr/lib64/libQt5Core.so.5
#8  0x00007f1b3dc99744 in start_thread () at /lib64/libpthread.so.0
#9  0x00007f1b4061faad in clone () at /lib64/libc.so.6

Thread 4 (Thread 0x7f1b1144d700 (LWP 6201)):
#0  0x00007f1b4061720d in poll () at /lib64/libc.so.6
#1  0x00007f1b3b571314 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f1b3b57142c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f1b4143113b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#4  0x00007f1b413dec2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f1b4122302a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007f1b12876887 in KCupsConnection::run() () at /usr/lib64/libkcupslib.so
#7  0x00007f1b4122774d in  () at /usr/lib64/libQt5Core.so.5
#8  0x00007f1b3dc99744 in start_thread () at /lib64/libpthread.so.0
#9  0x00007f1b4061faad in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7f1b3035c700 (LWP 6191)):
#0  0x00007f1b4061720d in poll () at /lib64/libc.so.6
#1  0x00007f1b3b571314 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f1b3b57142c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f1b4143113b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#4  0x00007f1b413dec2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f1b4122302a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007f1b418b37e5 in  () at /usr/lib64/libQt5DBus.so.5
#7  0x00007f1b4122774d in  () at /usr/lib64/libQt5Core.so.5
#8  0x00007f1b3dc99744 in start_thread () at /lib64/libpthread.so.0
#9  0x00007f1b4061faad in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7f1b3200f700 (LWP 6190)):
#0  0x00007f1b4061720d in poll () at /lib64/libc.so.6
#1  0x00007f1b46d9d3e2 in  () at /usr/lib64/libxcb.so.1
#2  0x00007f1b46d9efcf in xcb_wait_for_event () at /usr/lib64/libxcb.so.1
#3  0x00007f1b33927809 in  () at /usr/lib64/libQt5XcbQpa.so.5
#4  0x00007f1b4122774d in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007f1b3dc99744 in start_thread () at /lib64/libpthread.so.0
#6  0x00007f1b4061faad in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7f1b48406940 (LWP 6189)):
[KCrash Handler]
#6  0x00007f1b467012a9 in Plasma::Applet::immutability() const () at /usr/lib64/libKF5Plasma.so.5
#7  0x00007f1b46701359 in Plasma::Applet::destroy() () at /usr/lib64/libKF5Plasma.so.5
#8  0x00007f1b2c3526b9 in SystemTrayContainer::~SystemTrayContainer() (this=0x107f3310, __in_chrg=<optimized out>) at /usr/src/debug/plasma-workspace-5.10.90git~20170719T202021~e967385b/applets/systemtray/container/systemtraycontainer.cpp:38
#9  0x00007f1b2c3526d9 in SystemTrayContainer::~SystemTrayContainer() (this=0x107f3310, __in_chrg=<optimized out>) at /usr/src/debug/plasma-workspace-5.10.90git~20170719T202021~e967385b/applets/systemtray/container/systemtraycontainer.cpp:40
#10 0x00007f1b41408105 in QObjectPrivate::deleteChildren() () at /usr/lib64/libQt5Core.so.5
#11 0x00007f1b4141233e in QObject::~QObject() () at /usr/lib64/libQt5Core.so.5
#12 0x00007f1b46704469 in Plasma::Containment::~Containment() () at /usr/lib64/libKF5Plasma.so.5
#13 0x00007f1b4140b780 in QObject::event(QEvent*) () at /usr/lib64/libQt5Core.so.5
#14 0x00007f1b42399afc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#15 0x00007f1b423a0840 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#16 0x00007f1b413e0935 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#17 0x00007f1b413e2f13 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib64/libQt5Core.so.5
#18 0x00007f1b414318f3 in  () at /usr/lib64/libQt5Core.so.5
#19 0x00007f1b3b571134 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#20 0x00007f1b3b571388 in  () at /usr/lib64/libglib-2.0.so.0
#21 0x00007f1b3b57142c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#22 0x00007f1b4143111c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#23 0x00007f1b413dec2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#24 0x00007f1b413e71f4 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#25 0x00000000004385ee in main ()

Report to https://github.com/psifidotos/Latte-Dock/issues
```

![spectacle bc9730](https://user-images.githubusercontent.com/24593950/28499227-f43308da-6fb0-11e7-81d6-8dded8f6610d.png)

**Comment by psifidotos** [comment]
this is a systray crash... i dont know having multiple systrays if it works flawlessly... after you restart Latte it happens again?

**Comment by JenaPlinsky** [comment]
No never I can't replicate this

**Comment by psifidotos** [comment]
I think it happens sometimes only the first time a dock containing a second or third systray is created....  I havent found a way to reproduce it always in order to report it upstream but it can occur also with plasma panels crashing plasmashell
