### ISSUE TITLE
[Very Rare Crash] - close the latte setup window by clicking on the desktop for "not behave as normal dock" windows

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#632]
[Crash] - occurs when I close the milk setup window by clicking on the desktop
```
Application: Latte Dock (latte-dock), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7fc5510ad940 (LWP 12345))]

Thread 4 (Thread 0x7fc536d2f700 (LWP 12349)):
#0  0x00007fc544257899 in g_mutex_lock () at /usr/lib64/libglib-2.0.so.0
#1  0x00007fc544215390 in g_main_context_acquire () at /usr/lib64/libglib-2.0.so.0
#2  0x00007fc5442161d5 in  () at /usr/lib64/libglib-2.0.so.0
#3  0x00007fc54421642c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#4  0x00007fc54a0d613b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007fc54a083c2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#6  0x00007fc549ec802a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#7  0x00007fc54e06ef78 in  () at /usr/lib64/libQt5Qml.so.5
#8  0x00007fc549ecc74d in  () at /usr/lib64/libQt5Core.so.5
#9  0x00007fc54693e744 in start_thread () at /lib64/libpthread.so.0
#10 0x00007fc5492c4aad in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7fc539001700 (LWP 12347)):
#0  0x00007ffe771e1ab3 in clock_gettime ()
#1  0x00007fc5492d1576 in clock_gettime () at /lib64/libc.so.6
#2  0x00007fc54a0d5b61 in  () at /usr/lib64/libQt5Core.so.5
#3  0x00007fc54a0d4539 in QTimerInfoList::updateCurrentTime() () at /usr/lib64/libQt5Core.so.5
#4  0x00007fc54a0d4ab5 in QTimerInfoList::timerWait(timespec&) () at /usr/lib64/libQt5Core.so.5
#5  0x00007fc54a0d5f0e in  () at /usr/lib64/libQt5Core.so.5
#6  0x00007fc54421595d in g_main_context_prepare () at /usr/lib64/libglib-2.0.so.0
#7  0x00007fc544216230 in  () at /usr/lib64/libglib-2.0.so.0
#8  0x00007fc54421642c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#9  0x00007fc54a0d613b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#10 0x00007fc54a083c2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#11 0x00007fc549ec802a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#12 0x00007fc54a5587e5 in  () at /usr/lib64/libQt5DBus.so.5
#13 0x00007fc549ecc74d in  () at /usr/lib64/libQt5Core.so.5
#14 0x00007fc54693e744 in start_thread () at /lib64/libpthread.so.0
#15 0x00007fc5492c4aad in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7fc53acb4700 (LWP 12346)):
#0  0x00007fc5492bc20d in poll () at /lib64/libc.so.6
#1  0x00007fc54fa423e2 in  () at /usr/lib64/libxcb.so.1
#2  0x00007fc54fa43fcf in xcb_wait_for_event () at /usr/lib64/libxcb.so.1
#3  0x00007fc53c5cc879 in  () at /usr/lib64/libQt5XcbQpa.so.5
#4  0x00007fc549ecc74d in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007fc54693e744 in start_thread () at /lib64/libpthread.so.0
#6  0x00007fc5492c4aad in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7fc5510ad940 (LWP 12345)):
[KCrash Handler]
#6  0x00007fc54e593f80 in QQuickWindow::maybeUpdate() () at /usr/lib64/libQt5Quick.so.5
#7  0x00007fc54e57f3cb in QQuickItem::setX(double) () at /usr/lib64/libQt5Quick.so.5
#8  0x00007fc54e574570 in  () at /usr/lib64/libQt5Quick.so.5
#9  0x00007fc54e574cff in  () at /usr/lib64/libQt5Quick.so.5
#10 0x00007fc54e5791b9 in QQuickItem::geometryChanged(QRectF const&, QRectF const&) () at /usr/lib64/libQt5Quick.so.5
#11 0x00007fc54e57f753 in QQuickItem::setWidth(double) () at /usr/lib64/libQt5Quick.so.5
#12 0x00007fc54e58c3ae in  () at /usr/lib64/libQt5Quick.so.5
#13 0x00007fc54e05aa16 in  () at /usr/lib64/libQt5Qml.so.5
#14 0x00007fc54e05b455 in  () at /usr/lib64/libQt5Qml.so.5
#15 0x00007fc54e058f24 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () at /usr/lib64/libQt5Qml.so.5
#16 0x00007fc54e05972e in QQmlBinding::expressionChanged() () at /usr/lib64/libQt5Qml.so.5
#17 0x00007fc54e030f27 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () at /usr/lib64/libQt5Qml.so.5
#18 0x00007fc54dfd48ec in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () at /usr/lib64/libQt5Qml.so.5
#19 0x00007fc54a0aef52 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib64/libQt5Core.so.5
#20 0x00007fc54e57923c in QQuickItem::geometryChanged(QRectF const&, QRectF const&) () at /usr/lib64/libQt5Quick.so.5
#21 0x00007fc54e57f753 in QQuickItem::setWidth(double) () at /usr/lib64/libQt5Quick.so.5
#22 0x00007fc54e58c3ae in  () at /usr/lib64/libQt5Quick.so.5
#23 0x00007fc54e05aa16 in  () at /usr/lib64/libQt5Qml.so.5
#24 0x00007fc54e05b455 in  () at /usr/lib64/libQt5Qml.so.5
#25 0x00007fc54e058f24 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () at /usr/lib64/libQt5Qml.so.5
#26 0x00007fc54e05972e in QQmlBinding::expressionChanged() () at /usr/lib64/libQt5Qml.so.5
#27 0x00007fc54e030f27 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () at /usr/lib64/libQt5Qml.so.5
#28 0x00007fc54dfd48ec in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () at /usr/lib64/libQt5Qml.so.5
#29 0x00007fc54a0aef52 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib64/libQt5Core.so.5
#30 0x00007fc54dfd0794 in QQmlVMEMetaObject::metaCall(QObject*, QMetaObject::Call, int, void**) () at /usr/lib64/libQt5Qml.so.5
#31 0x00007fc54e05a9bd in  () at /usr/lib64/libQt5Qml.so.5
#32 0x00007fc54e05b455 in  () at /usr/lib64/libQt5Qml.so.5
#33 0x00007fc54e058f24 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () at /usr/lib64/libQt5Qml.so.5
#34 0x00007fc54e05972e in QQmlBinding::expressionChanged() () at /usr/lib64/libQt5Qml.so.5
#35 0x00007fc54e030f27 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () at /usr/lib64/libQt5Qml.so.5
#36 0x00007fc54dfd48ec in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () at /usr/lib64/libQt5Qml.so.5
#37 0x00007fc54a0aef52 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib64/libQt5Core.so.5
#38 0x00007fc54dfd0794 in QQmlVMEMetaObject::metaCall(QObject*, QMetaObject::Call, int, void**) () at /usr/lib64/libQt5Qml.so.5
#39 0x00007fc54e05a9bd in  () at /usr/lib64/libQt5Qml.so.5
#40 0x00007fc54e05b455 in  () at /usr/lib64/libQt5Qml.so.5
#41 0x00007fc54e058f24 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () at /usr/lib64/libQt5Qml.so.5
#42 0x00007fc54e05972e in QQmlBinding::expressionChanged() () at /usr/lib64/libQt5Qml.so.5
#43 0x00007fc54e030f27 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () at /usr/lib64/libQt5Qml.so.5
#44 0x00007fc54dfd48ec in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () at /usr/lib64/libQt5Qml.so.5
#45 0x00007fc54a0aef52 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib64/libQt5Core.so.5
#46 0x00007fc54dfd0794 in QQmlVMEMetaObject::metaCall(QObject*, QMetaObject::Call, int, void**) () at /usr/lib64/libQt5Qml.so.5
#47 0x00007fc54e05a9bd in  () at /usr/lib64/libQt5Qml.so.5
#48 0x00007fc54e05b455 in  () at /usr/lib64/libQt5Qml.so.5
#49 0x00007fc54e058f24 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () at /usr/lib64/libQt5Qml.so.5
#50 0x00007fc54e05972e in QQmlBinding::expressionChanged() () at /usr/lib64/libQt5Qml.so.5
#51 0x00007fc54e030f27 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () at /usr/lib64/libQt5Qml.so.5
#52 0x00007fc54dfd48ec in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () at /usr/lib64/libQt5Qml.so.5
#53 0x00007fc54a0aef52 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib64/libQt5Core.so.5
#54 0x00007fc54dfd0794 in QQmlVMEMetaObject::metaCall(QObject*, QMetaObject::Call, int, void**) () at /usr/lib64/libQt5Qml.so.5
#55 0x00007fc54dfe4859 in QQmlPropertyPrivate::write(QObject*, QQmlPropertyData const&, QVariant const&, QQmlContextData*, QFlags<QQmlPropertyData::WriteFlag>) () at /usr/lib64/libQt5Qml.so.5
#56 0x00007fc54e49f63e in  () at /usr/lib64/libQt5Quick.so.5
#57 0x00007fc54e08573b in QAbstractAnimationJob::setCurrentTime(int) () at /usr/lib64/libQt5Qml.so.5
#58 0x00007fc54e08597f in QQmlAnimationTimer::updateAnimationsTime(long long) () at /usr/lib64/libQt5Qml.so.5
#59 0x00007fc549ea28f5 in QUnifiedTimer::updateAnimationTimers(long long) () at /usr/lib64/libQt5Core.so.5
#60 0x00007fc549ea348c in QAnimationDriver::advanceAnimation(long long) () at /usr/lib64/libQt5Core.so.5
#61 0x00007fc54a0b0504 in QObject::event(QEvent*) () at /usr/lib64/libQt5Core.so.5
#62 0x00007fc54b03eafc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#63 0x00007fc54b045840 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#64 0x00007fc54a085935 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#65 0x00007fc54a0d57ae in QTimerInfoList::activateTimers() () at /usr/lib64/libQt5Core.so.5
#66 0x00007fc54a0d5df1 in  () at /usr/lib64/libQt5Core.so.5
#67 0x00007fc544216134 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#68 0x00007fc544216388 in  () at /usr/lib64/libglib-2.0.so.0
#69 0x00007fc54421642c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#70 0x00007fc54a0d611c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#71 0x00007fc54a083c2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#72 0x00007fc54a08c1f4 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#73 0x000000000043a0be in main ()

```

**Comment by psifidotos** [comment]
entire qt crash... and I cant reproduce of course in my system...

**Comment by psifidotos** [comment]
since when?  can you track which commit introduced this ? does it happen always?

**Comment by JenaPlinsky** [comment]
it is a very rare crash i think

**Comment by JenaPlinsky** [comment]
I can only say this...
- my configuration is brand new
- I have only one dock in only one activity
- and latte is up to the penultimate commit

**Comment by psifidotos** [comment]
without reproduce steps qml crashes are extremely difficult to fix or an indicator which commit introduced the instability...

these backtraces dont provide any valuable info

**Comment by psifidotos** [comment]
this crash could be what changing the **normal dock behavior** because afterwards Latte has to recreate dock... please check again with latest master that it is still valid...

**Comment by JenaPlinsky** [comment]
I would close the thread what do you say?
If it re occur then we can open a new one
maybe with more detailed information

**Comment by psifidotos** [comment]
ok
