### ISSUE TITLE
[ Crash ] - Crash on Layout change (no activity)

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#642]
![spectacle eo9268](https://user-images.githubusercontent.com/24593950/28790341-ffb58308-7628-11e7-8874-465416082c4d.png)

Crash on **layout** change (no activity)
from MyPlasma to MyLatte
![spectacle vm9268](https://user-images.githubusercontent.com/24593950/28789682-c1a350f6-7626-11e7-998d-c96f12772f02.png)
![spectacle jl9268](https://user-images.githubusercontent.com/24593950/28789748-ff2f3778-7626-11e7-93ca-a70db0f01e45.png)
![spectacle sf9268](https://user-images.githubusercontent.com/24593950/28789766-119e1d84-7627-11e7-8108-4f768123a2dc.png)
![spectacle kk9268](https://user-images.githubusercontent.com/24593950/28789780-1fb0dd44-7627-11e7-9037-dd0738055695.png)

This is the layout that should have loaded ... but I had two crashes in 5 attempts
![spectacle jv9268](https://user-images.githubusercontent.com/24593950/28790049-ebb26eda-7627-11e7-906a-8a7a7f67bfd6.png)

If, kcrash run the restart command, load the layout related to the current activity
![spectacle ir9268](https://user-images.githubusercontent.com/24593950/28789908-75f7d298-7627-11e7-8e3d-56f8e6d9e586.png)

```
Application: Latte Dock (latte-dock), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f73e160d940 (LWP 5397))]

Thread 5 (Thread 0x7f73aaca4700 (LWP 5410)):
#0  0x00007f73d4775a3b in g_main_context_prepare () at /usr/lib64/libglib-2.0.so.0
#1  0x00007f73d4776230 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f73d477642c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f73da63613b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#4  0x00007f73da5e3c2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f73da42802a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007f73ac0cd887 in KCupsConnection::run() () at /usr/lib64/libkcupslib.so
#7  0x00007f73da42c74d in  () at /usr/lib64/libQt5Core.so.5
#8  0x00007f73d6e9e744 in start_thread () at /lib64/libpthread.so.0
#9  0x00007f73d9824aad in clone () at /lib64/libc.so.6

Thread 4 (Thread 0x7f73c728f700 (LWP 5401)):
#0  0x00007f73d981828d in read () at /lib64/libc.so.6
#1  0x00007f73d47b6750 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f73d4775e49 in g_main_context_check () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f73d47762a8 in  () at /usr/lib64/libglib-2.0.so.0
#4  0x00007f73d477642c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#5  0x00007f73da63613b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#6  0x00007f73da5e3c2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#7  0x00007f73da42802a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#8  0x00007f73de5cef78 in  () at /usr/lib64/libQt5Qml.so.5
#9  0x00007f73da42c74d in  () at /usr/lib64/libQt5Core.so.5
#10 0x00007f73d6e9e744 in start_thread () at /lib64/libpthread.so.0
#11 0x00007f73d9824aad in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7f73c9561700 (LWP 5399)):
#0  0x00007f73d981c20d in poll () at /lib64/libc.so.6
#1  0x00007f73d4776314 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f73d477642c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f73da63613b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#4  0x00007f73da5e3c2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#5  0x00007f73da42802a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
#6  0x00007f73daab87e5 in  () at /usr/lib64/libQt5DBus.so.5
#7  0x00007f73da42c74d in  () at /usr/lib64/libQt5Core.so.5
#8  0x00007f73d6e9e744 in start_thread () at /lib64/libpthread.so.0
#9  0x00007f73d9824aad in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7f73cb214700 (LWP 5398)):
#0  0x00007f73d981c20d in poll () at /lib64/libc.so.6
#1  0x00007f73dffa23e2 in  () at /usr/lib64/libxcb.so.1
#2  0x00007f73dffa3fcf in xcb_wait_for_event () at /usr/lib64/libxcb.so.1
#3  0x00007f73ccb2c879 in  () at /usr/lib64/libQt5XcbQpa.so.5
#4  0x00007f73da42c74d in  () at /usr/lib64/libQt5Core.so.5
#5  0x00007f73d6e9e744 in start_thread () at /lib64/libpthread.so.0
#6  0x00007f73d9824aad in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7f73e160d940 (LWP 5397)):
[KCrash Handler]
#6  0x00007f73df937e64 in std::__atomic_base<int>::load(std::memory_order) const (__m=std::memory_order_relaxed, this=0x10) at /usr/include/c++/4.8/bits/atomic_base.h:496
```

**Comment by psifidotos** [comment]
This is upstrem, qt or graphics driver...
