### ISSUE TITLE
Crash when switching layout

### ISSUE THREAD

**Issue by tstdin** [psifidotos/Latte-Dock#699]
latte-dock-0.7.0-1.fc26.src.rpm from Fedora Testing

After choosing another layout in Latte settings -> Appearance -> Layout, application crashes with Segmentation fault

Sorry I didn't use the ddd debuging style mentioned in wiki, it didn't work out of the box:
```
 $ ddd --gdb --debugger latte-dock
Warning: Cannot convert string "-*-symbol-*-*-*-*-*-120-*-*-*-*-adobe-*" to type FontStruct
```

 ```
$ gdb -q latte-dock
Reading symbols from latte-dock...Reading symbols from /usr/lib/debug/usr/bin/latte-dock.debug...done.
done.
(gdb) run
Starting program: /usr/bin/latte-dock 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.25-9.fc26.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7f7d5b29c700 (LWP 22080)]
[New Thread 0x7f7d4c7d2700 (LWP 22097)]
[New Thread 0x7f7d49a46700 (LWP 22098)]
Detaching after fork from child process 22099.
[New Thread 0x7f7d291dc700 (LWP 22116)]
[New Thread 0x7f7d13e51700 (LWP 22117)]
Detaching after fork from child process 22216.

Thread 1 "latte-dock" received signal SIGSEGV, Segmentation fault.
0x00007f7d6bf1c7e4 in Plasma::Containment::corona() const () from /lib64/libKF5Plasma.so.5
Missing separate debuginfos, use: dnf debuginfo-install GConf2-3.2.6-17.fc26.x86_64 OpenEXR-libs-2.2.0-6.fc26.x86_64 avahi-libs-0.6.32-7.fc26.x86_64 bzip2-libs-1.0.6-22.fc26.x86_64 compat-openssl10-1.0.2j-6.fc26.x86_64 cups-libs-2.2.2-6.fc26.x86_64 dbus-glib-0.108-2.fc26.x86_64 dbus-libs-1.11.16-1.fc26.x86_64 dbusmenu-qt5-0.9.3-0.12.20150604.fc26.x86_64 expat-2.2.4-1.fc26.x86_64 flac-libs-1.3.2-2.fc26.x86_64 fontconfig-2.12.1-4.fc26.x86_64 freetype-2.7.1-9.fc26.x86_64 gamin-0.1.10-25.fc26.x86_64 glib2-2.52.3-1.fc26.x86_64 gmp-6.1.2-4.fc26.x86_64 gnutls-3.5.14-1.fc26.x86_64 graphite2-1.3.10-1.fc26.x86_64 gsm-1.0.17-1.fc26.x86_64 harfbuzz-1.4.4-1.fc26.x86_64 ilmbase-2.2.0-8.fc26.x86_64 jasper-libs-2.0.12-1.fc26.x86_64 jbigkit-libs-2.1-6.fc26.x86_64 kde-connect-1.0.3-2.fc26.x86_64 kde-connect-libs-1.0.3-2.fc26.x86_64 kde-print-manager-16.12.3-1.fc26.x86_64 kde-print-manager-libs-16.12.3-1.fc26.x86_64 keyutils-libs-1.5.10-1.fc26.x86_64 kf5-attica-5.36.0-1.fc26.x86_64 kf5-frameworkintegration-libs-5.36.0-1.fc26.x86_64 kf5-kactivities-libs-5.36.0-1.fc26.x86_64 kf5-kactivities-stats-5.36.0-1.fc26.x86_64 kf5-karchive-5.36.0-1.fc26.x86_64 kf5-kauth-5.36.0-1.fc26.x86_64 kf5-kbookmarks-5.36.0-1.fc26.x86_64 kf5-kcmutils-5.36.0-1.fc26.x86_64 kf5-kcodecs-5.36.0-1.fc26.x86_64 kf5-kcompletion-5.36.0-1.fc26.x86_64 kf5-kconfig-core-5.36.0-1.fc26.x86_64 kf5-kconfig-gui-5.36.0-1.fc26.x86_64 kf5-kconfigwidgets-5.36.0-1.fc26.x86_64 kf5-kcoreaddons-5.36.0-1.fc26.x86_64 kf5-kcrash-5.36.0-1.fc26.x86_64 kf5-kdbusaddons-5.36.0-1.fc26.x86_64 kf5-kdeclarative-5.36.0-1.fc26.x86_64 kf5-kdelibs4support-libs-5.36.0-1.fc26.x86_64 kf5-kglobalaccel-libs-5.36.0-1.fc26.x86_64 kf5-kguiaddons-5.36.0-2.fc26.x86_64 kf5-ki18n-5.36.0-3.fc26.x86_64 kf5-kiconthemes-5.36.0-1.fc26.x86_64 kf5-kidletime-5.36.0-1.fc26.x86_64 kf5-kimageformats-5.36.0-1.fc26.x86_64 kf5-kio-core-libs-5.36.0-1.fc26.x86_64 kf5-kio-file-widgets-5.36.0-1.fc26.x86_64 kf5-kio-widgets-libs-5.36.0-1.fc26.x86_64 kf5-kitemmodels-5.36.0-1.fc26.x86_64 kf5-kitemviews-5.36.0-1.fc26.x86_64 kf5-kjobwidgets-5.36.0-1.fc26.x86_64 kf5-knotifications-5.36.0-1.fc26.x86_64 kf5-knotifyconfig-5.36.0-1.fc26.x86_64 kf5-kpackage-5.36.0-1.fc26.x86_64 kf5-kparts-5.36.0-1.fc26.x86_64 kf5-kpeople-5.36.0-1.fc26.x86_64 kf5-krunner-5.36.0-1.fc26.x86_64 kf5-kservice-5.36.0-1.fc26.x86_64 kf5-ktextwidgets-5.36.0-1.fc26.x86_64 kf5-kunitconversion-5.36.0-1.fc26.x86_64 kf5-kwallet-libs-5.36.0-1.fc26.x86_64 kf5-kwayland-5.36.0-1.fc26.x86_64 kf5-kwidgetsaddons-5.36.0-1.fc26.x86_64 kf5-kwindowsystem-5.36.0-1.fc26.x86_64 kf5-kxmlgui-5.36.0-1.fc26.x86_64 kf5-modemmanager-qt-5.36.0-1.fc26.x86_64 kf5-networkmanager-qt-5.36.0-1.fc26.x86_64 kf5-plasma-5.36.0-1.fc26.x86_64 kf5-solid-libs-5.36.0-1.fc26.x86_64 kf5-sonnet-core-5.36.0-1.fc26.x86_64 kf5-sonnet-ui-5.36.0-1.fc26.x86_64 kf5-threadweaver-5.36.0-1.fc26.x86_64 krb5-libs-1.15.1-25.fc26.x86_64 ktp-common-internals-16.12.3-1.fc26.x86_64 lcms2-2.8-3.fc26.x86_64 libICE-1.0.9-9.fc26.x86_64 libSM-1.2.2-5.fc26.x86_64 libX11-1.6.5-2.fc26.x86_64 libXau-1.0.8-7.fc26.x86_64 libXcursor-1.1.14-8.fc26.x86_64 libXdamage-1.1.4-9.fc26.x86_64 libXext-1.3.3-5.fc26.x86_64 libXfixes-5.0.3-2.fc26.x86_64 libXi-1.7.9-2.fc26.x86_64 libXrender-0.9.10-2.fc26.x86_64 libXtst-1.2.3-2.fc26.x86_64 libXxf86vm-1.1.4-4.fc26.x86_64 libacl-2.2.52-15.fc26.x86_64 libasyncns-0.8-11.fc26.x86_64 libattr-2.4.47-18.fc26.x86_64 libblkid-2.30.1-1.fc26.x86_64 libcanberra-0.30-13.fc26.x86_64 libcap-2.25-5.fc26.x86_64 libcom_err-1.43.4-2.fc26.x86_64 libcrypt-nss-2.25-9.fc26.x86_64 libdrm-2.4.82-1.fc26.x86_64 libepoxy-1.4.3-1.fc26.x86_64 libevdev-1.5.7-1.fc26.x86_64 libffi-3.1-12.fc26.x86_64 libgcc-7.1.1-3.fc26.x86_64 libgcrypt-1.7.8-1.fc26.x86_64 libglvnd-0.2.999-24.20170818git8d4d03f.fc26.x86_64 libglvnd-egl-0.2.999-24.20170818git8d4d03f.fc26.x86_64 libglvnd-glx-0.2.999-24.20170818git8d4d03f.fc26.x86_64 libgpg-error-1.25-2.fc26.x86_64 libgudev-230-4.fc26.x86_64 libicu-57.1-6.fc26.x86_64 libidn2-2.0.3-1.fc26.x86_64 libinput-1.8.0-2.fc26.x86_64 libjpeg-turbo-1.5.1-0.fc26.x86_64 libksysguard-5.10.5-1.fc26.x86_64 libkworkspace5-5.10.5-2.fc26.x86_64 libmng-2.0.3-4.fc26.x86_64 libmodman-2.0.1-13.fc26.x86_64 libmount-2.30.1-1.fc26.x86_64 libogg-1.3.2-6.fc26.x86_64 libpciaccess-0.13.4-4.fc26.x86_64 libpng-1.6.28-2.fc26.x86_64 libproxy-0.4.15-2.fc26.x86_64 libselinux-2.6-7.fc26.x86_64 libsndfile-1.0.28-6.fc26.x86_64 libstdc++-7.1.1-3.fc26.x86_64 libtasn1-4.12-1.fc26.x86_64 libtdb-1.3.13-1.fc26.x86_64 libtiff-4.0.8-1.fc26.x86_64 libtool-ltdl-2.4.6-17.fc26.x86_64 libtxc_dxtn-1.0.1-2.gitef072983.fc26.x86_64 libunistring-0.9.7-1.fc26.x86_64 libuuid-2.30.1-1.fc26.x86_64 libvorbis-1.3.5-2.fc26.x86_64 libwacom-0.26-1.fc26.x86_64 libwayland-client-1.13.0-1.fc26.x86_64 libwebp-0.6.0-2.fc26.x86_64 libxcb-1.12-3.fc26.x86_64 libxkbcommon-0.7.1-3.fc26.x86_64 libxkbcommon-x11-0.7.1-3.fc26.x86_64 libxml2-2.9.4-2.fc26.x86_64 libxshmfence-1.2-4.fc26.x86_64 lz4-libs-1.8.0-1.fc26.x86_64 mesa-dri-drivers-17.1.7-1.fc26.x86_64 mesa-libGL-17.1.7-1.fc26.x86_64 mesa-libglapi-17.1.7-1.fc26.x86_64 mtdev-1.1.5-7.fc26.x86_64 nettle-3.3-2.fc26.x86_64 nss-softokn-freebl-3.32.0-1.2.fc26.x86_64 p11-kit-0.23.8-1.fc26.x86_64 pcre-8.41-1.fc26.x86_64 pcre-utf16-8.41-1.fc26.x86_64 phonon-qt5-4.9.1-3.fc26.x86_64 plasma-breeze-5.10.5-1.fc26.x86_64 plasma-desktop-5.10.5-1.fc26.x86_64 plasma-integration-5.10.5-1.fc26.x86_64 plasma-nm-5.10.5-1.fc26.x86_64 plasma-pa-5.10.5-1.fc26.x86_64 plasma-workspace-5.10.5-2.fc26.x86_64 plasma-workspace-libs-5.10.5-2.fc26.x86_64 pulseaudio-libs-10.0-4.fc26.x86_64 pulseaudio-libs-glib2-10.0-4.fc26.x86_64 qca-qt5-2.1.3-6.fc26.x86_64 qt5-qtbase-5.7.1-19.fc26.x86_64 qt5-qtbase-gui-5.7.1-19.fc26.x86_64 qt5-qtdeclarative-5.7.1-8.fc26.x86_64 qt5-qtgraphicaleffects-5.7.1-4.fc26.x86_64 qt5-qtimageformats-5.7.1-5.fc26.x86_64 qt5-qtquickcontrols-5.7.1-4.fc26.x86_64 qt5-qtsvg-5.7.1-3.fc26.x86_64 qt5-qtx11extras-5.7.1-3.fc26.x86_64 sqlite-libs-3.20.0-2.fc26.x86_64 systemd-libs-233-6.fc26.x86_64 tcp_wrappers-libs-7.6-85.fc26.x86_64 telepathy-glib-0.24.1-5.fc26.x86_64 telepathy-logger-0.8.2-4.fc26.x86_64 telepathy-logger-qt-15.04.0-4.fc26.x86_64 telepathy-qt5-0.9.7-2.fc26.x86_64 xcb-util-0.4.0-6.fc26.x86_64 xcb-util-image-0.4.0-5.fc26.x86_64 xcb-util-keysyms-0.4.0-4.fc26.x86_64 xcb-util-renderutil-0.3.9-7.fc26.x86_64 xcb-util-wm-0.4.1-9.fc26.x86_64 xz-libs-5.2.3-2.fc26.x86_64 zlib-1.2.11-2.fc26.x86_64
(gdb) bt full
#0  0x00007f7d6bf1c7e4 in Plasma::Containment::corona() const ()                
    at /lib64/libKF5Plasma.so.5                                                 
#1  0x000000010006018f in Latte::DockConfigView::setupWaylandIntegration() (this=this@entry=0x10437a520)                                                        
    at /usr/src/debug/Latte-Dock-0.7.0/app/dockconfigview.cpp:291
        c = <optimized out>
#2  0x0000000100061caf in Latte::DockConfigView::event(QEvent*) (this=0x10437a520, e=0x7fffffffcb90)
    at /usr/src/debug/Latte-Dock-0.7.0/app/dockconfigview.cpp:324
        pe = <optimized out>
#3  0x00007f7d689a55dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#4  0x00007f7d689acc74 in QApplication::notify(QObject*, QEvent*) ()
    at /lib64/libQt5Widgets.so.5
#5  0x00007f7d680cf627 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#6  0x00007f7d6849b200 in QWindowPrivate::create(bool) ()
    at /lib64/libQt5Gui.so.5
#7  0x00007f7d6849afda in QWindow::setVisible(bool) () at /lib64/libQt5Gui.so.5
#8  0x000000010005b5dd in Latte::DockView::~DockView() (this=0x10057c900, __in_chrg=<optimized out>) at /usr/src/debug/Latte-Dock-0.7.0/app/dockview.cpp:154
#9  0x000000010005b619 in Latte::DockView::~DockView() (this=0x10057c900, __in_chrg=<optimized out>) at /usr/src/debug/Latte-Dock-0.7.0/app/dockview.cpp:164
#10 0x00007f7d680f78f8 in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#11 0x00007f7d6849d398 in QWindow::event(QEvent*) () at /lib64/libQt5Gui.so.5
---Type <return> to continue, or q <return> to quit---
#12 0x00007f7d6b30d645 in QQuickWindow::event(QEvent*) ()
    at /lib64/libQt5Quick.so.5
#13 0x000000010005b76b in Latte::DockView::event(QEvent*) (this=0x10057c900, e=0x1003e63a0) at /usr/src/debug/Latte-Dock-0.7.0/app/dockview.cpp:1357
#14 0x00007f7d689a55dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#15 0x00007f7d689acc74 in QApplication::notify(QObject*, QEvent*) ()
    at /lib64/libQt5Widgets.so.5
#16 0x00007f7d680cf627 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#17 0x00007f7d680d185b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt5Core.so.5
#18 0x00007f7d6811ddd3 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5Core.so.5
#19 0x00007f7d5f85c247 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#20 0x00007f7d5f85c5e8 in g_main_context_iterate.isra ()
    at /lib64/libglib-2.0.so.0
#21 0x00007f7d5f85c67c in g_main_context_iteration ()
    at /lib64/libglib-2.0.so.0
#22 0x00007f7d6811de4f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#23 0x00007f7d680ce60a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#24 0x00007f7d680d627c in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#25 0x0000000100035c88 in main(int, char**) (argc=<optimized out>, argv=<optimiz---Type <return> to continue, or q <return> to quit---
ed out>) at /usr/src/debug/Latte-Dock-0.7.0/app/main.cpp:150
        app = <incomplete type>
        parser = {d = 0x100383970}
        lockFile = {d_ptr = {d = 0x1003a49a0}}
        timeout = <optimized out>
        corona = 
          {<Plasma::Corona> = {<No data fields>}, static staticMetaObject = {d = {superdata = 0x7f7d6c19f280 <Plasma::Corona::staticMetaObject>, stringdata = 0x1000a65a0 <qt_meta_stringdata_Latte__DockCorona>, data = 0x1000a6360 <qt_meta_data_Latte__DockCorona>, static_metacall = 0x100097ea0 <Latte::DockCorona::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, m_activitiesStarting = false, m_tasksWillBeLoaded = true, m_firstContainmentWithTasks = 1, m_dockViews = {{d = 0x10100a7e0, e = 0x10100a7e0}}, m_waitingDockViews = {{d = 0x7f7d6818a360 <QHashData::shared_null>, e = 0x7f7d6818a360 <QHashData::shared_null>}}, m_alternativesObjects = {<QListSpecialMethods<KDeclarative::QmlObject*>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x7f7d6818a3c0 <QListData::shared_null>}, d = 0x7f7d6818a3c0 <QListData::shared_null>}}, m_docksScreenSyncTimer = <incomplete type>, m_activityConsumer = 0x100374ff0, aboutDialog = {wp = {d = 0x0, value = 0x0}}, m_screenPool = 0x1003c97d0, m_globalShortcuts = 0x1003c9a20, m_universalSettings = 0x1003d3ca0, m_layoutManager = 0x1003d4af0, m_waylandDockCorona = 0x0}
        service = <incomplete type>
```

**Comment by psifidotos** [comment]
1. is that happening always?
2. how do you switch layout?
3. does it happen with all layouts?

**Comment by psifidotos** [comment]
4. is that happening on wayland?

**Comment by tstdin** [comment]
1. Yes, happening always.
2. Right click on dock, then Latte settings and under Appearance tab I choose another layout (Plasma, Unity, My Layout)
3. Yes
4. Didn't test on Wayland, I'm currently running X11

**Comment by psifidotos** [comment]
Can you please test from the right click context menu if this crash is also happening is your system?

- right click on the Latte dock -> Layouts -> change layout

**Comment by tstdin** [comment]
Now I realized that when I don't just click on another layout in dropdown menu and instead choose is under the configure menu, it doesn't crash.

**Comment by psifidotos** [comment]
yes, but either way... this is correct bug and crash!!! :)
I can fix it... :) it isnt difficult... you probably use Qt 5.9 and it sends a signal that I had assumed that is sent only for wayland... but as it appears it is sent also for x11
