### ISSUE TITLE
Unable to build with ruby 2.5.0

### ISSUE THREAD

**Issue by marhkb** [psifidotos/Latte-Dock#830]
Arch updated ruby to version 2.5.0 and Latte refuses to build.

```
[100%] Downloading translations for latte-dock branch trunk...
Bereits aktuell.
Logging colors are not available. Install logger-colors gem if desired
- Ruby 2.1.0 or 2.2.0 or 2.3.0 or 2.4.0 required.
  Currently using: 2.5.0
Traceback (most recent call last):
        9: from /home/marcus/.cache/pacaur/latte-dock-git/src/latte-dock/build/releaseme/fetchpo.rb:23:in `<main>'
        8: from /home/marcus/.cache/pacaur/latte-dock-git/src/latte-dock/build/releaseme/fetchpo.rb:23:in `require_relative'
        7: from /home/marcus/.cache/pacaur/latte-dock-git/src/latte-dock/build/releaseme/lib/releaseme.rb:22:in `<top (required)>'
        6: from /home/marcus/.cache/pacaur/latte-dock-git/src/latte-dock/build/releaseme/lib/releaseme.rb:22:in `require_relative'
        5: from /home/marcus/.cache/pacaur/latte-dock-git/src/latte-dock/build/releaseme/lib/releaseme/cmakeeditor.rb:24:in `<top (required)>'
        4: from /home/marcus/.cache/pacaur/latte-dock-git/src/latte-dock/build/releaseme/lib/releaseme/cmakeeditor.rb:24:in `require_relative'
        3: from /home/marcus/.cache/pacaur/latte-dock-git/src/latte-dock/build/releaseme/lib/releaseme/logable.rb:28:in `<top (required)>'
        2: from /home/marcus/.cache/pacaur/latte-dock-git/src/latte-dock/build/releaseme/lib/releaseme/logable.rb:28:in `require_relative'
        1: from /home/marcus/.cache/pacaur/latte-dock-git/src/latte-dock/build/releaseme/lib/releaseme/requirements.rb:3:in `<top (required)>'
/home/marcus/.cache/pacaur/latte-dock-git/src/latte-dock/build/releaseme/lib/releaseme/requirement_checker.rb:108:in `check': Not all requirements met. (RuntimeError)
make[3]: *** [CMakeFiles/fetch-translations.dir/build.make:61: CMakeFiles/fetch-translations] Fehler 1
make[2]: *** [CMakeFiles/Makefile2:836: CMakeFiles/fetch-translations.dir/all] Fehler 2
make[1]: *** [CMakeFiles/Makefile2:843: CMakeFiles/fetch-translations.dir/rule] Fehler 2
make: *** [Makefile:487: fetch-translations] Fehler 2
```

**Comment by psifidotos** [comment]
is there a reason you are using releaseme ?

**Comment by psifidotos** [comment]
this is an issue with releaseme perl script and must be reported to kde devs... I dont think is Latte specific, it should influence all kde projects...

**Comment by marhkb** [comment]
No special reason. It is the latte-dock-git AUR package.

**Comment by psifidotos** [comment]
> No special reason. It is the latte-dock-git AUR package.

this is an issue with releaseme perl script and must be reported to kde devs... I dont think is Latte specific, it should influence all kde projects...

**Comment by omni6** [comment]
@psifidotos 
Of course your install.sh now generates the same issue using --translations on any distro with ruby > 2.4.3.

How to handle?

**Comment by psifidotos** [comment]
> How to handle?

you dont have that issue with other kde apps e.g. dolphin?

**Comment by omni6** [comment]
Most kde apps are binaries from official repo. dolphin-git/kate-git does not contain `make fetch-translations` (pkgbuild is over 2 yrs old).
But i maintain `audex-git` pkgbuild and there i have the same issue.

**Comment by psifidotos** [comment]
> But i maintain audex-git pkgbuild and there i have the same issue.

someone must contact the kde devs and inform them for the breakage

**Comment by omni6** [comment]
ok, i will file a bug on bugtracking system..

**Comment by omni6** [comment]
https://bugs.kde.org/show_bug.cgi?id=388627

**Comment by omni6** [comment]
fixed!
