### ISSUE TITLE
16.04: Segfault during start

### ISSUE THREAD

**Issue by pat-s** [psifidotos/Latte-Dock#877]
```
KDE Plasma: 5.8.8 (xenial-backports)
KDE Frameworks: 3.36.0
QT: 5.6.1
Latte-dock: 0.6.2
```

When launched via Plasma search, i.e. ALT+Space, it segfaults.
I have to start it once via terminal and then it also loads via the Desktop launcher.

Not sure if the debug output is of any use but I'll attach it:

```
Application: Latte Dock (latte-dock), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f5bee664900 (LWP 10856))]

Thread 4 (Thread 0x7f5bd17f3700 (LWP 10859)):
#0  0x00007f5be9a2b27d in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f5be1b92073 in ?? () from /usr/lib/nvidia-384/tls/libnvidia-tls.so.384.111
#2  0x00007f5be54df6f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f5be549be74 in g_main_context_check () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f5be549c330 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f5be549c49c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007f5bea56d37b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f5bea515ffa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f5bea33e9e4 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f5bec6406b5 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#10 0x00007f5bea343808 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f5be59bd6ba in start_thread (arg=0x7f5bd17f3700) at pthread_create.c:333
#12 0x00007f5be9a3b41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7f5bd313e700 (LWP 10858)):
#0  0x00007f5be9a2b27d in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f5be1b92073 in ?? () from /usr/lib/nvidia-384/tls/libnvidia-tls.so.384.111
#2  0x00007f5be54df6f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f5be549be74 in g_main_context_check () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f5be549c330 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f5be549c49c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007f5bea56d37b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f5bea515ffa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f5bea33e9e4 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f5bee7b5515 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#10 0x00007f5bea343808 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f5be59bd6ba in start_thread (arg=0x7f5bd313e700) at pthread_create.c:333
#12 0x00007f5be9a3b41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f5bd9123700 (LWP 10857)):
#0  0x00007f5be9a2f74d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f5bed79dc62 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f5bed79f8d7 in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f5bdb899d29 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f5bea343808 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f5be59bd6ba in start_thread (arg=0x7f5bd9123700) at pthread_create.c:333
#6  0x00007f5be9a3b41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f5bee664900 (LWP 10856)):
[KCrash Handler]
#6  0x00007f5bec640cd0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#7  0x00007f5bec5eaf69 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#8  0x00007f5bec5e3c91 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#9  0x00007f5bec5c5bb9 in QQmlComponentPrivate::loadUrl(QUrl const&, QQmlComponent::CompilationMode) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#10 0x00007f5becb63490 in ?? () from /usr/lib/x86_64-linux-gnu/libKF5Declarative.so.5
#11 0x00007f5bee403e76 in PlasmaQuick::AppletQuickItem::init() () from /usr/lib/x86_64-linux-gnu/libKF5PlasmaQuick.so.5
#12 0x00007f5bd1809964 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/plasma/scriptengines/plasma_appletscript_declarative.so
#13 0x00007f5bee405828 in PlasmaQuick::AppletQuickItem::itemChange(QQuickItem::ItemChange, QQuickItem::ItemChangeData const&) () from /usr/lib/x86_64-linux-gnu/libKF5PlasmaQuick.so.5
#14 0x00007f5bec8ff19e in QQuickItemPrivate::refWindow(QQuickWindow*) () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#15 0x00007f5bec901884 in QQuickItem::setParentItem(QQuickItem*) () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#16 0x00007f5bec904431 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#17 0x00007f5bec904a4b in QQuickItem::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#18 0x00007f5bee4058a5 in PlasmaQuick::AppletQuickItem::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib/x86_64-linux-gnu/libKF5PlasmaQuick.so.5
#19 0x00007f5bd180a6e5 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/plasma/scriptengines/plasma_appletscript_declarative.so
#20 0x00007f5bea526010 in QMetaProperty::write(QObject*, QVariant const&) const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007f5bea54c98f in QObject::setProperty(char const*, QVariant const&) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007f5bd181162e in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/plasma/scriptengines/plasma_appletscript_declarative.so
#23 0x00007f5bea544c24 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007f5bed305b1f in Plasma::Containment::appletAdded(Plasma::Applet*) () from /usr/lib/x86_64-linux-gnu/libKF5Plasma.so.5
#25 0x00007f5bed3079ed in Plasma::Containment::addApplet(Plasma::Applet*) () from /usr/lib/x86_64-linux-gnu/libKF5Plasma.so.5
#26 0x00007f5bb92dfeee in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/plasma/applets/org.kde.plasma.private.systemtray.so
#27 0x00007f5bb92e31b5 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/plasma/applets/org.kde.plasma.private.systemtray.so
#28 0x00007f5bb92e47d8 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/plasma/applets/org.kde.plasma.private.systemtray.so
#29 0x00007f5bb92e746e in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/plasma/applets/org.kde.plasma.private.systemtray.so
#30 0x00007f5bb92e796b in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/plasma/applets/org.kde.plasma.private.systemtray.so
#31 0x00007f5bec5c036a in QQmlPropertyPrivate::write(QObject*, QQmlPropertyData const&, QVariant const&, QQmlContextData*, QFlags<QQmlPropertyPrivate::WriteFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#32 0x00007f5bec58e43e in QV4::QObjectWrapper::setProperty(QV4::ExecutionEngine*, QObject*, QQmlPropertyData*, QV4::Value const&) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#33 0x00007f5bec58eeb6 in QV4::QObjectWrapper::setQmlProperty(QV4::ExecutionEngine*, QQmlContextData*, QObject*, QV4::String*, QV4::QObjectWrapper::RevisionMode, QV4::Value const&) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#34 0x00007f5bec58efe2 in QV4::QObjectWrapper::put(QV4::Managed*, QV4::String*, QV4::Value const&) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#35 0x00007f5bec59ee36 in QV4::Runtime::setProperty(QV4::ExecutionEngine*, QV4::Value const&, int, QV4::Value const&) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#36 0x00007f5bb92c18d7 in ?? ()
#37 0x0000000001ed4650 in ?? ()
#38 0x35f590463ceece00 in ?? ()
#39 0x0000000001ed7930 in ?? ()
#40 0x00007f5bd07ec3f0 in ?? ()
#41 0x0000000001ed4650 in ?? ()
#42 0x35f590463ceece00 in ?? ()
#43 0x0000000000000000 in ?? ()
```

**Comment by psifidotos** [comment]
unfortunately I can no longer support v0.6.x ... it is very old codebase...

**Comment by pat-s** [comment]
v0.7.x will not work not work on 16.04 with Plasma 5.8.8 right? Otherwise I would build it from source.

**Comment by psifidotos** [comment]
> v0.7.x will not work not work on 16.04 with Plasma 5.8.8 right? 

yes but 16.04 is not the problem but rather the plasma 5.8.8. I use Neon which is 16.04 but provides plasma 5.12 these days...

**Comment by pat-s** [comment]
I see, so the outdated Kubuntu is the problem. I tried neon once but got problems with other applications due to the neon-patched repos of some libraries. 
I'll just wait until 18.04 is stable. Thanks for your work :)
