### ISSUE TITLE
Segfault when opening Audio Volume

### ISSUE THREAD

**Issue by DrDoctor13** [psifidotos/Latte-Dock#918]
I clicked the Audio Volume applet to adjust an Appilcation volume and Latte segfaulted as soon as I clicked on it. Attached is the debug info:

```
Application: Latte Dock (latte-dock), signal: Segmentation fault
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f2e062c8800 (LWP 20729))]

Thread 15 (Thread 0x7f2d8496c700 (LWP 22146)):
#0  0x00007f2dffe2b3d8 in read () at /usr/lib/libc.so.6
#1  0x00007f2df3fb57c2 in pa_read () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#2  0x00007f2df784d7af in pa_mainloop_prepare () at /usr/lib/libpulse.so.0
#3  0x00007f2df784e241 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007f2df784e301 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#5  0x00007f2df785c6ae in  () at /usr/lib/libpulse.so.0
#6  0x00007f2df3fe581c in  () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#7  0x00007f2dfb89708c in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007f2dffe39e7f in clone () at /usr/lib/libc.so.6

Thread 14 (Thread 0x7f2d875ef700 (LWP 21996)):
#0  0x00007f2dfb89d3bd in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2e0074a02c in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib/libQt5Core.so.5
#2  0x00007f2e03f8f41a in  () at /usr/lib/libQt5Quick.so.5
#3  0x00007f2e03f8f8a4 in  () at /usr/lib/libQt5Quick.so.5
#4  0x00007f2e00748b4d in  () at /usr/lib/libQt5Core.so.5
#5  0x00007f2dfb89708c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2dffe39e7f in clone () at /usr/lib/libc.so.6

Thread 13 (Thread 0x7f2d93952700 (LWP 14787)):
#0  0x00007f2dfb89d3bd in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2e0074a02c in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib/libQt5Core.so.5
#2  0x00007f2e03f8f41a in  () at /usr/lib/libQt5Quick.so.5
#3  0x00007f2e03f8f8a4 in  () at /usr/lib/libQt5Quick.so.5
#4  0x00007f2e00748b4d in  () at /usr/lib/libQt5Core.so.5
#5  0x00007f2dfb89708c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2dffe39e7f in clone () at /usr/lib/libc.so.6

Thread 12 (Thread 0x7f2d92d12700 (LWP 13351)):
#0  0x00007f2dfb89d3bd in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2e0074a02c in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib/libQt5Core.so.5
#2  0x00007f2e03f8f41a in  () at /usr/lib/libQt5Quick.so.5
#3  0x00007f2e03f8f8a4 in  () at /usr/lib/libQt5Quick.so.5
#4  0x00007f2e00748b4d in  () at /usr/lib/libQt5Core.so.5
#5  0x00007f2dfb89708c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2dffe39e7f in clone () at /usr/lib/libc.so.6

Thread 11 (Thread 0x7f2da1220700 (LWP 13070)):
#0  0x00007f2dfb89d3bd in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2e0074a02c in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib/libQt5Core.so.5
#2  0x00007f2e03f8f41a in  () at /usr/lib/libQt5Quick.so.5
#3  0x00007f2e03f8f8a4 in  () at /usr/lib/libQt5Quick.so.5
#4  0x00007f2e00748b4d in  () at /usr/lib/libQt5Core.so.5
#5  0x00007f2dfb89708c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2dffe39e7f in clone () at /usr/lib/libc.so.6

Thread 10 (Thread 0x7f2d73fff700 (LWP 12790)):
#0  0x00007f2dfb89d3bd in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2e0074a02c in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib/libQt5Core.so.5
#2  0x00007f2e03f8f41a in  () at /usr/lib/libQt5Quick.so.5
#3  0x00007f2e03f8f8a4 in  () at /usr/lib/libQt5Quick.so.5
#4  0x00007f2e00748b4d in  () at /usr/lib/libQt5Core.so.5
#5  0x00007f2dfb89708c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2dffe39e7f in clone () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7f2d92511700 (LWP 12159)):
#0  0x00007f2dfb89d3bd in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2e0074a02c in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib/libQt5Core.so.5
#2  0x00007f2e03f8f41a in  () at /usr/lib/libQt5Quick.so.5
#3  0x00007f2e03f8f8a4 in  () at /usr/lib/libQt5Quick.so.5
#4  0x00007f2e00748b4d in  () at /usr/lib/libQt5Core.so.5
#5  0x00007f2dfb89708c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2dffe39e7f in clone () at /usr/lib/libc.so.6

Thread 8 (Thread 0x7f2d90c3f700 (LWP 11030)):
#0  0x00007f2dfb89d3bd in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2e0074a02c in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib/libQt5Core.so.5
#2  0x00007f2e03f8f41a in  () at /usr/lib/libQt5Quick.so.5
#3  0x00007f2e03f8f8a4 in  () at /usr/lib/libQt5Quick.so.5
#4  0x00007f2e00748b4d in  () at /usr/lib/libQt5Core.so.5
#5  0x00007f2dfb89708c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2dffe39e7f in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7f2dc9d82700 (LWP 10926)):
#0  0x00007f2dfb89d3bd in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2e0074a02c in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib/libQt5Core.so.5
#2  0x00007f2e03f8f41a in  () at /usr/lib/libQt5Quick.so.5
#3  0x00007f2e03f8f8a4 in  () at /usr/lib/libQt5Quick.so.5
#4  0x00007f2e00748b4d in  () at /usr/lib/libQt5Core.so.5
#5  0x00007f2dfb89708c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2dffe39e7f in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7f2dc3fff700 (LWP 10925)):
#0  0x00007f2dfb89d3bd in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2e0074a02c in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib/libQt5Core.so.5
#2  0x00007f2e03f8f41a in  () at /usr/lib/libQt5Quick.so.5
#3  0x00007f2e03f8f8a4 in  () at /usr/lib/libQt5Quick.so.5
#4  0x00007f2e00748b4d in  () at /usr/lib/libQt5Core.so.5
#5  0x00007f2dfb89708c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2dffe39e7f in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7f2da3b9e700 (LWP 20787)):
#0  0x00007f2dfb89d3bd in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2e0074a02c in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib/libQt5Core.so.5
#2  0x00007f2e03f8f41a in  () at /usr/lib/libQt5Quick.so.5
#3  0x00007f2e03f8f8a4 in  () at /usr/lib/libQt5Quick.so.5
#4  0x00007f2e00748b4d in  () at /usr/lib/libQt5Core.so.5
#5  0x00007f2dfb89708c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2dffe39e7f in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7f2dba268700 (LWP 20743)):
#0  0x00007f2dffe2f97b in poll () at /usr/lib/libc.so.6
#1  0x00007f2df8fa8ff3 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f2df8fa910e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f2e00992314 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007f2e009343db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007f2e007437ae in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007f2dc0cf51ba in KCupsConnection::run() () at /usr/lib/libkcupslib.so
#7  0x00007f2e00748b4d in  () at /usr/lib/libQt5Core.so.5
#8  0x00007f2dfb89708c in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007f2dffe39e7f in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7f2de7178700 (LWP 20732)):
#0  0x00007f2dffe2b3d8 in read () at /usr/lib/libc.so.6
#1  0x00007f2df8fee7d1 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f2df8fa8ac8 in g_main_context_check () at /usr/lib/libglib-2.0.so.0
#3  0x00007f2df8fa8f96 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007f2df8fa910e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#5  0x00007f2e00992314 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#6  0x00007f2e009343db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#7  0x00007f2e007437ae in QThread::exec() () at /usr/lib/libQt5Core.so.5
#8  0x00007f2e03abe379 in  () at /usr/lib/libQt5Qml.so.5
#9  0x00007f2e00748b4d in  () at /usr/lib/libQt5Core.so.5
#10 0x00007f2dfb89708c in start_thread () at /usr/lib/libpthread.so.0
#11 0x00007f2dffe39e7f in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7f2ded62f700 (LWP 20731)):
#0  0x00007f2dffe2f97b in poll () at /usr/lib/libc.so.6
#1  0x00007f2df8fa8ff3 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f2df8fa910e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f2e00992314 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007f2e009343db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007f2e007437ae in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007f2e0206b416 in  () at /usr/lib/libQt5DBus.so.5
#7  0x00007f2e00748b4d in  () at /usr/lib/libQt5Core.so.5
#8  0x00007f2dfb89708c in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007f2dffe39e7f in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7f2e062c8800 (LWP 20729)):
[KCrash Handler]
#4  0x00007f2e039e5bf5 in QV4::QObjectWrapper::getProperty(QV4::ExecutionEngine*, QObject*, int, bool) () at /usr/lib/libQt5Qml.so.5
#5  0x00007f2e039fdddc in QV4::Runtime::method_getQmlQObjectProperty(QV4::ExecutionEngine*, QV4::Value const&, int, bool) () at /usr/lib/libQt5Qml.so.5
#6  0x00007f2dc8717b6e in  ()
#7  0x0000000100000040 in  ()
#8  0x0000561e62643dc0 in  ()
#9  0x00007ffefa894510 in  ()
#10 0x00007f2e03fdb3ac in  () at /usr/lib/libQt5Quick.so.5
#11 0x00007f2e03aa4013 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () at /usr/lib/libQt5Qml.so.5
#12 0x00007f2e03a78b03 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () at /usr/lib/libQt5Qml.so.5
#13 0x00007f2e03a120aa in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () at /usr/lib/libQt5Qml.so.5
#14 0x00007f2e00965edf in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#15 0x00007f2e03a0dff1 in QQmlVMEMetaObject::metaCall(QObject*, QMetaObject::Call, int, void**) () at /usr/lib/libQt5Qml.so.5
#16 0x00007f2e03a24cf3 in  () at /usr/lib/libQt5Qml.so.5
#17 0x00007f2e03a21e76 in QQmlPropertyPrivate::write(QObject*, QQmlPropertyData const&, QVariant const&, QQmlContextData*, QFlags<QQmlPropertyData::WriteFlag>) () at /usr/lib/libQt5Qml.so.5
#18 0x00007f2e039ea8c6 in QV4::QObjectWrapper::setProperty(QV4::ExecutionEngine*, QObject*, QQmlPropertyData*, QV4::Value const&) () at /usr/lib/libQt5Qml.so.5
#19 0x00007f2e039eb2f7 in QV4::QObjectWrapper::setQmlProperty(QV4::ExecutionEngine*, QQmlContextData*, QObject*, QV4::String*, QV4::QObjectWrapper::RevisionMode, QV4::Value const&) () at /usr/lib/libQt5Qml.so.5
#20 0x00007f2e039eb40c in QV4::QObjectWrapper::put(QV4::Managed*, QV4::String*, QV4::Value const&) () at /usr/lib/libQt5Qml.so.5
#21 0x00007f2e039fb29d in QV4::Runtime::method_setProperty(QV4::ExecutionEngine*, QV4::Value const&, int, QV4::Value const&) () at /usr/lib/libQt5Qml.so.5
#22 0x00007f2dc800dc7e in  ()
#23 0x0000000000000003 in  ()
#24 0x00007f2de6139418 in  ()
#25 0x0000561e61e72d40 in  ()
#26 0x00007f2e0394959a in QV4::ExecutionContext::newCallContext(QV4::Function*, QV4::CallData*) () at /usr/lib/libQt5Qml.so.5
#27 0x00007f2e0394be8d in QV4::ExecutionContext::call(QV4::Scope&, QV4::CallData*, QV4::Function*, QV4::FunctionObject const*) () at /usr/lib/libQt5Qml.so.5
#28 0x00007f2e03a9cf17 in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*, QV4::Scope&) () at /usr/lib/libQt5Qml.so.5
#29 0x00007f2e03a2fda1 in QQmlBoundSignalExpression::evaluate(void**) () at /usr/lib/libQt5Qml.so.5
#30 0x00007f2e03a31474 in  () at /usr/lib/libQt5Qml.so.5
#31 0x00007f2e03a78b03 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () at /usr/lib/libQt5Qml.so.5
#32 0x00007f2e03a120aa in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () at /usr/lib/libQt5Qml.so.5
#33 0x00007f2e00965edf in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#34 0x00007f2e05cd37f3 in PlasmaQuick::AppletQuickItem::expandedChanged(bool) () at /usr/lib/libKF5PlasmaQuick.so.5
#35 0x00007f2e05cd5c9a in PlasmaQuick::AppletQuickItem::setExpanded(bool) () at /usr/lib/libKF5PlasmaQuick.so.5
#36 0x00007f2e05cd8bdd in  () at /usr/lib/libKF5PlasmaQuick.so.5
#37 0x00007f2e05cdac2b in PlasmaQuick::AppletQuickItem::qt_metacall(QMetaObject::Call, int, void**) () at /usr/lib/libKF5PlasmaQuick.so.5
#38 0x00007f2de718ebc6 in  () at /usr/lib/qt/plugins/plasma/scriptengines/plasma_appletscript_declarative.so
#39 0x00007f2e03a24cf3 in  () at /usr/lib/libQt5Qml.so.5
#40 0x00007f2e03a21a4b in QQmlPropertyPrivate::write(QObject*, QQmlPropertyData const&, QVariant const&, QQmlContextData*, QFlags<QQmlPropertyData::WriteFlag>) () at /usr/lib/libQt5Qml.so.5
#41 0x00007f2e039ea8c6 in QV4::QObjectWrapper::setProperty(QV4::ExecutionEngine*, QObject*, QQmlPropertyData*, QV4::Value const&) () at /usr/lib/libQt5Qml.so.5
#42 0x00007f2e039eb2f7 in QV4::QObjectWrapper::setQmlProperty(QV4::ExecutionEngine*, QQmlContextData*, QObject*, QV4::String*, QV4::QObjectWrapper::RevisionMode, QV4::Value const&) () at /usr/lib/libQt5Qml.so.5
#43 0x00007f2e039eb40c in QV4::QObjectWrapper::put(QV4::Managed*, QV4::String*, QV4::Value const&) () at /usr/lib/libQt5Qml.so.5
#44 0x00007f2e039fb29d in QV4::Runtime::method_setProperty(QV4::ExecutionEngine*, QV4::Value const&, int, QV4::Value const&) () at /usr/lib/libQt5Qml.so.5
#45 0x00007f2dc8089cd3 in  ()
#46 0x0000000000000000 in  ()

```

**Comment by psifidotos** [comment]
1. Does it crash always?
2. The applet is in the systray or the panel?
3. If it is in the panel is it crashing when it is animated?
4. probably this crash should be reported upstream to plasma because I dont see any Latte code in it... but lets first answer [1-3]

**Comment by DrDoctor13** [comment]
1. No. It also happened when trying to change whether an icon was hidden or not in the System Tray.
2. In the systray.
3. The first one, yes. The second one, I'm not 100% sure.

**Comment by psifidotos** [comment]
> In the systray

Latte doesnt change anything for the systray

> No. It also happened when trying to change whether an icon was hidden or not in the System Tray.

an already reported plasma bug

please report upstream at bugs.kde.org ...
